"""`teyla harness status|sync` and `teyla rule|correct`: the plugin's skills, hooks and policy
in Cursor, Codex, Grok and Hermes, written into a fake HOME."""
from __future__ import annotations

import json
import pathlib

import pytest

from teyla import harness, policy, rules


@pytest.fixture
def home(tmp_path, monkeypatch):
    h = tmp_path / "home"
    for d in (".cursor", ".codex", ".grok", ".hermes"):
        (h / d).mkdir(parents=True)
    (h / ".hermes" / "config.yaml").write_text("model:\n  default: grok-4.6\n")
    (h / ".agents").mkdir()
    (h / ".agents" / "POLICY.md").write_text("# policy\n\n## 1. ladder\n\ntext\n")
    monkeypatch.setattr(harness, "HOME", h)
    monkeypatch.setattr(harness, "HOOKS_DIR", h / ".teyla" / "hooks")
    monkeypatch.setattr(policy, "HOME", h)
    monkeypatch.setattr(policy, "POLICY", h / ".agents" / "POLICY.md")
    monkeypatch.setattr(policy, "TARGETS", {
        "claude-code": h / ".claude" / "CLAUDE.md", "codex": h / ".codex" / "AGENTS.md",
        "grok": h / ".grok" / "AGENTS.md", "hermes": h / ".hermes" / "SOUL.md",
        "cursor": h / ".cursor" / "skills" / "teyla-policy" / "SKILL.md"})
    return h


def test_sync_writes_skills_hooks_and_is_idempotent(home):
    lines = harness.sync(home=home)
    assert any("copied session-start.sh" in l for l in lines)
    # five skills per harness, hooks for the three that have a mechanism
    for h in ("cursor", "codex", "grok"):
        for s in harness.skill_names():
            assert (home / f".{h}" / "skills" / s / "SKILL.md").exists(), (h, s)
    for s in harness.skill_names():
        assert (home / ".hermes" / "skills" / "teyla" / s / "SKILL.md").exists()
    cur = json.loads((home / ".cursor" / "hooks.json").read_text())
    assert cur["version"] == 1 and set(cur["hooks"]) == {"sessionStart", "beforeSubmitPrompt"}
    assert cur["hooks"]["beforeSubmitPrompt"][0]["command"].endswith("/.teyla/hooks/capture-correction.sh")
    grok = json.loads((home / ".grok" / "hooks" / "teyla.json").read_text())
    assert set(grok["hooks"]) == {"SessionStart", "UserPromptSubmit"}
    yaml = (home / ".hermes" / "config.yaml").read_text()
    assert yaml.startswith("model:") and "hooks:\n  on_session_start:" in yaml and "pre_llm_call:" in yaml
    assert harness.HERMES_BEGIN in yaml and harness.HERMES_END in yaml
    scripts = home / ".teyla" / "hooks"
    assert (scripts / "capture-correction.sh").stat().st_mode & 0o111
    # second run: nothing to do
    assert harness.sync(home=home) == ["in sync: cursor, codex, grok, hermes"]
    rows = {r["harness"]: r for r in harness.status(home=home)}
    assert rows["cursor"]["skills"] == 5 and rows["cursor"]["hooks"] is True
    assert rows["codex"]["hooks"] is None and rows["grok"]["hooks"] is True and rows["hermes"]["hooks"] is True
    text = harness.render_status(harness.status(home=home))
    assert "codex    yes      wired    5/5      n/a" in text or "5/5" in text


def test_sync_keeps_a_users_cursor_hooks_and_refuses_a_foreign_hermes_block(home):
    cur = home / ".cursor" / "hooks.json"
    cur.write_text(json.dumps({"version": 1, "hooks": {"beforeShellExecution": [{"command": ".cursor/hooks/mine.sh"}],
                                                      "sessionStart": [{"command": "/x/other.sh"}]}}))
    (home / ".hermes" / "config.yaml").write_text("hooks:\n  pre_tool_call:\n    - command: /x/guard.sh\n")
    lines = harness.sync(home=home)
    d = json.loads(cur.read_text())
    assert d["hooks"]["beforeShellExecution"] == [{"command": ".cursor/hooks/mine.sh"}]
    assert [e["command"] for e in d["hooks"]["sessionStart"]][0] == "/x/other.sh"
    assert len(d["hooks"]["sessionStart"]) == 2
    assert any("hermes" in l and "by hand" in l for l in lines)
    assert (home / ".hermes" / "config.yaml").read_text().startswith("hooks:\n  pre_tool_call:")
    rows = {r["harness"]: r for r in harness.status(home=home)}
    assert rows["hermes"]["hooks"] is False


def test_absent_harness_is_left_alone(home, tmp_path):
    import shutil
    shutil.rmtree(home / ".codex"); shutil.rmtree(home / ".hermes")
    lines = harness.sync(home=home)
    assert not (home / ".codex").exists() and not (home / ".hermes").exists()
    assert not any("codex" in l or "hermes" in l for l in lines)
    rows = {r["harness"]: r for r in harness.status(home=home)}
    assert rows["codex"]["present"] is False


def test_rendered_skill_is_harness_neutral_and_says_where_it_came_from():
    text = harness.render_skill("harvest", "codex")
    assert text.startswith("---\nname: teyla-harvest\ndescription: ")
    assert "/teyla:rule" not in text and "`teyla rule`" in text
    assert "generated by `teyla harness sync`" in text and "plugin/skills/harvest/SKILL.md" in text
    assert "disable-model-invocation" not in text
    assert "disable-model-invocation: false" in harness.render_skill("harvest", "cursor")
    rule = harness.render_skill("teyla-rule", "grok")
    assert 'teyla rule "<the sentence>"' in rule and "plugin/commands/rule.md" in rule


def test_policy_sync_writes_the_cursor_policy_skill(home):
    st = policy.status()
    assert st["cursor"] is False
    done = policy.sync()
    assert any("Cursor user skill" in d for d in done)
    p = home / ".cursor" / "skills" / "teyla-policy" / "SKILL.md"
    assert p.read_text().startswith("---\nname: teyla-policy\n") and p.read_text().endswith("text\n")
    assert policy.status()["cursor"] is True
    (home / ".agents" / "POLICY.md").write_text("# policy v2\n")
    assert policy.status()["cursor"] is False
    policy.sync()
    assert policy.status()["cursor"] is True


# --- teyla rule / teyla correct ----------------------------------------------------------------

def test_rule_writes_scoped_file_mirrors_into_real_agents_md_and_refuses_duplicates(tmp_path):
    repo = tmp_path / "repo"; repo.mkdir()
    (repo / "AGENTS.md").write_text("# guide\n\nsome text\n")
    out = rules.add_rule(repo, "Outbound drafts open with a claim, not a question", scope="gtm/**")
    f = repo / ".claude" / "rules" / "outbound-drafts-open-claim.md"
    assert f.read_text() == "---\nglobs: gtm/**\n---\n\n- Outbound drafts open with a claim, not a question.\n"
    assert (repo / "AGENTS.md").read_text().endswith("## Rules\n\n- Outbound drafts open with a claim, not a question.\n")
    assert out[0].startswith("wrote .claude/rules/outbound-drafts-open-claim.md")
    # exact and near-exact duplicates are refused
    again = rules.add_rule(repo, "outbound drafts open with a claim, not a question.")
    assert again == ["already there: .claude/rules/outbound-drafts-open-claim.md — nothing written"]
    # a second rule in the same cluster appends a bullet, scope kept
    rules.add_rule(repo, "Outbound drafts never name a prospect outside runs/", scope="**")
    assert (repo / "AGENTS.md").read_text().count("- Outbound") == 2
    assert len(list((repo / ".claude" / "rules").glob("*.md"))) == 2
    # dry run writes nothing
    before = sorted(p.name for p in (repo / ".claude" / "rules").glob("*.md"))
    rules.add_rule(repo, "Never use npm here, always pnpm", dry=True)
    assert sorted(p.name for p in (repo / ".claude" / "rules").glob("*.md")) == before


def test_rule_skips_a_symlinked_agents_md_and_fills_cursor_rules_when_present(tmp_path):
    repo = tmp_path / "repo"; repo.mkdir()
    (repo / "CLAUDE.md").write_text("# claude\n")
    (repo / "AGENTS.md").symlink_to("CLAUDE.md")
    (repo / ".cursor" / "rules").mkdir(parents=True)
    out = rules.add_rule(repo, "Never use npm here, always pnpm", scope="**/package.json")
    assert any("symlink" in l for l in out)
    assert (repo / "CLAUDE.md").read_text() == "# claude\n"
    [mdc] = list((repo / ".cursor" / "rules").glob("*.mdc"))
    assert mdc.name == "npm-pnpm.mdc"
    assert "globs: **/package.json" in mdc.read_text() and "alwaysApply: false" in mdc.read_text()
    assert mdc.read_text().endswith("- Never use npm here, always pnpm.\n")


def test_correct_records_a_line_and_says_how_to_promote(tmp_path):
    repo = tmp_path / "repo"; repo.mkdir()
    out = rules.record_correction(repo, "no, the gate opens at 14:30 not 14:00")
    rec = json.loads((repo / ".teyla" / "corrections.jsonl").read_text())
    assert rec["text"].startswith("no, the gate") and rec["cwd"] == str(repo.resolve()) and rec["ts"].endswith("+00:00")
    assert out[0].endswith("(1 so far)") and any("teyla rule" in l for l in out)
