"""`teyla cloud prep <repo> [--dry] [--allow-public] [--fix-gitignore]` — put into a repo's
working tree what a cloud session needs to finish, as plain files (a cloud VM installs no
plugins, not even ones the repo's settings declare):

    AGENTS.md                  a Shipping section between <!-- teyla:cloud:start/end -->: the
                               repo-safe part of the owner's policy, `merge-approved: yes|no`
                               from the owner's list, and the cloud definition of done
    CLAUDE.md                  `@AGENTS.md` at the top, inside markers, when CLAUDE.md is its
                               own file (a CLAUDE.md ⇄ AGENTS.md symlink needs nothing)
    .claude/settings.json      SessionStart + Stop hooks, merged into what is there
    .claude/hooks/teyla-cloud-start.sh   orientation, printed only when CLAUDE_CODE_REMOTE=true
    .claude/hooks/teyla-cloud-stop.sh    exit 2 while work is unpushed or has no PR (cloud only)
    .claude/rules/cloud.md     the rules that only apply in a cloud VM
    docs/cloud-setup.md        the setup script to paste into claude.ai, and the secret NAMES
                               from .env.example with where each goes
    .gitignore                 only with --fix-gitignore: `.claude/` wholesale → three lines

Idempotent: markdown goes between markers and everything outside them is left alone; a
script or rules file that exists without the generated header is hand-written and skipped.
`--dry` prints a unified diff of every file (no context lines: the output is meant to be
pasteable, and context would quote the repo's own text).

Everything written here may end up public, so the content is generic by construction and
checked before any write: no home-directory path, no email, no other repo from the owner's
list. A repo that is public — or whose visibility cannot be asked, which counts as public — is
refused unless --allow-public.
"""
from __future__ import annotations

import difflib
import json
import os
import pathlib
import re
import shlex

from . import cloud

START = "<!-- teyla:cloud:start — generated by `teyla cloud prep`; re-run it to refresh, edit outside these markers -->"
END = "<!-- teyla:cloud:end -->"
IMPORT_START = "<!-- teyla:cloud-import:start -->"
IMPORT_END = "<!-- teyla:cloud-import:end -->"
SCRIPT_HEAD = "# Generated by `teyla cloud prep` — re-run it to refresh; edits here are overwritten."
START_HOOK = ".claude/hooks/teyla-cloud-start.sh"
STOP_HOOK = ".claude/hooks/teyla-cloud-stop.sh"
GITIGNORE_LINES = (".claude/settings.local.json", ".claude/launch.json", ".claude/worktrees/")
_WHOLESALE = {".claude", ".claude/", "/.claude", "/.claude/", ".claude/*", "/.claude/*", ".claude/**", "/.claude/**"}

# The owner's policy says it three ways today; "No CI on `push` or `pull_request`" was missed
# and the Shipping section silently dropped the rule (caught in review, P2).
_NO_ACTIONS = re.compile(r"No GitHub Actions|GitHub Actions are off|No CI on\s+`?push`?\s*(?:or|/)\s*`?(pull_request|PR)\b", re.I)


class Refused(Exception):
    pass


# --- inputs ------------------------------------------------------------------------------

def owner_policy_text() -> str:
    """The owner's policy files, read only to decide which generic rules apply (today: whether
    GitHub Actions are off). Nothing from them is copied."""
    home = pathlib.Path.home()
    return "\n".join(cloud._read(p) for p in (home / ".claude" / "CLAUDE.md", home / ".agents" / "POLICY.md"))


def _gate(repo: pathlib.Path) -> tuple[str | None, list[str]]:
    g = cloud.gate_script(repo)
    if g is None:
        return None, []
    return "./" + str(g.relative_to(repo)), sorted({s["tool"] for s in cloud.mac_steps(cloud._read(g))})


# --- the generated content ---------------------------------------------------------------

def shipping_section(merge: str, gate: str | None, no_actions: bool) -> str:
    g = f"`{gate}`" if gate else "the repo's tests"
    L = [START, "## Shipping", "", f"merge-approved: {merge}", "",
         "- One PR per logical unit: what a reviewer reads in one sitting. Two unrelated fixes are two PRs.",
         "- Merge, don't squash (`gh pr merge --merge`): every commit stays in history.",
         "- Never force-push: not to the default branch, not to a shared branch.",
         ]
    if no_actions:
        # POLICY §10 in its own words: deploy jobs on push to main are allowed, so "no Actions
        # on push" overstated it and a cloud session could read a deploy workflow as a violation.
        L.append(f"- No CI on push/PR (short ubuntu deploy jobs on push to main allowed, POLICY §10); the local gate is {g}.")
    L += ["- Report honestly: what you could not verify goes in the same sentence as the claim.",
          "- Ask about product decisions with a proposed default; never ask for permission to proceed.",
          ("- This repo is merge-approved: a PR whose whole gate ran green may be merged without asking."
           if merge == "yes" else "- This repo is not merge-approved: open the PR and stop; the owner merges."),
          "", "### Done, in a cloud session", "",
          "A cloud session (`CLAUDE_CODE_REMOTE=true`) can push only to its own branch and has no Mac. It is done when:", "",
          f"1. {g} ran here and the PR body carries its output: the result, and every line saying what was skipped.",
          "2. The branch is pushed and a PR is open (`gh pr create --fill`, then a body: what changed, why, the gate output, what is unverified).",
          "3. A step that needs a Mac (Xcode, simulator, TestFlight, launchd, keychain) and was skipped puts the label `needs-mac` on the PR "
          "(`gh pr edit --add-label needs-mac`). That PR is not merged from the cloud: a local session builds, reviews and merges it.",
          "4. Second opinion: codex and grok are not installed here. Review the diff in a fresh pass and call it a \"same-provider review\" in the PR body.",
          ]
    if merge == "yes":
        L.append("5. Nothing skipped and the gate green: merge it (`gh pr merge --merge`). If merging is refused from here, the open PR is the done state.")
    L += [END]
    return "\n".join(L) + "\n"


def start_hook(gate: str | None, tools: list[str], merge: str) -> str:
    skips = ", ".join(tools) if tools else "nothing in the gate needs a Mac"
    gate_line = f"Gate: {gate} (run it before every push; its output goes in the PR body)" if gate else \
        "Gate: none in this repo; run the tests you can find and say which ran"
    return f"""#!/bin/sh
{SCRIPT_HEAD}
# SessionStart: orientation for a cloud session. Silent anywhere else: CLAUDE_CODE_REMOTE is
# "true" only on a cloud VM, and stdout of this hook reaches the model there.
[ "${{CLAUDE_CODE_REMOTE:-}}" = "true" ] || exit 0
cd "${{CLAUDE_PROJECT_DIR:-.}}" 2>/dev/null || exit 0
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "?")
cat <<EOF
Cloud session on branch $branch. This VM has the repository only: no Mac, and nothing from the owner's machine.
{gate_line}
Skipped here without a Mac: {skips}
merge-approved: {merge} (AGENTS.md, section Shipping)
Before you stop: push this branch and open the PR (gh pr create --fill); label it needs-mac if a Mac-only step was skipped. The Stop hook checks for the PR.
EOF
"""


def stop_hook(gate: str | None) -> str:
    g = gate or "the tests"
    return f"""#!/bin/sh
{SCRIPT_HEAD}
# Stop: in a cloud session, do not stop while this branch's work is uncommitted, unpushed, or
# has no PR. Exit 2 hands the message back to the model. A second stop in a row goes through
# (stop_hook_active), so a session that cannot push is told once, never trapped.
[ "${{CLAUDE_CODE_REMOTE:-}}" = "true" ] || exit 0
input=$(cat)
case "$input" in *'"stop_hook_active":true'*|*'"stop_hook_active": true'*) exit 0 ;; esac
cd "${{CLAUDE_PROJECT_DIR:-.}}" 2>/dev/null || exit 0
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null) || exit 0
[ "$branch" = "HEAD" ] && exit 0
base=$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null || echo origin/main)
if [ -n "$(git status --porcelain 2>/dev/null | head -1)" ]; then
  echo "Uncommitted changes on $branch: run {g}, commit, push, and open the PR before you stop." >&2
  exit 2
fi
# Unpushed = commits not on THIS branch's own remote ref: its upstream (@{{u}}) or origin/<branch>.
# A commit that only some other remote branch contains is not pushed for this branch's PR. A
# branch never pushed counts what it has past the default branch; with neither ref, what is on
# no remote at all. Asked before any "nothing to do" shortcut: a missing base ref used to count
# as 0 ahead and let committed, unpushed work stop (caught in review, P1). A question git cannot
# answer fails closed.
has_ref() {{ git rev-parse --verify --quiet "$1^{{commit}}" >/dev/null 2>&1; }}
up=$(git rev-parse --abbrev-ref --symbolic-full-name '@{{u}}' 2>/dev/null) || up=""
own=""
for r in "$up" "origin/$branch"; do
  [ -n "$r" ] && has_ref "$r" && own="$own $r"
done
if [ -n "$own" ]; then
  # shellcheck disable=SC2086 # $own is one or two ref names, split on purpose
  unpushed=$(git rev-list --count HEAD --not $own 2>/dev/null) || unpushed=""
elif has_ref "$base"; then
  unpushed=$(git rev-list --count "$base..HEAD" 2>/dev/null) || unpushed=""
else
  unpushed=$(git rev-list --count HEAD --not --remotes 2>/dev/null) || unpushed=""
fi
if [ -z "$unpushed" ]; then
  echo "Could not tell whether $branch is pushed (git rev-list failed). Push it (git push -u origin $branch) and open the PR before you stop." >&2
  exit 2
fi
if [ "$unpushed" != 0 ]; then
  if [ "$branch" = "${{base#origin/}}" ]; then
    echo "$unpushed commit(s) on the default branch $branch are not on the remote, and this session cannot push to it: move them to a branch (git switch -c claude/<name>), push that, and open the PR before you stop." >&2
  else
    echo "$unpushed commit(s) on $branch are not on the remote: git push -u origin $branch, then open the PR (gh pr create --fill) before you stop." >&2
  fi
  exit 2
fi
[ "$branch" = "${{base#origin/}}" ] && exit 0
if ! git rev-parse --verify --quiet "$base^{{commit}}" >/dev/null 2>&1 || \
   ! ahead=$(git rev-list --count "$base..HEAD" 2>/dev/null); then
  echo "Could not compare $branch with $base (the base ref is missing here), so whether it needs a PR is unknown. Open the PR (gh pr create --fill) or name the branch in your last message." >&2
  exit 2
fi
[ "$ahead" = 0 ] && exit 0
# An open PR for this branch covers whatever is pushed to it. A merged or closed one covers only
# the head it had: commits after it need a NEW PR, never "handled by the merged one".
if command -v gh >/dev/null 2>&1; then
  if ! open=$(gh pr list --head "$branch" --state open --json number --jq length 2>/dev/null); then
    if ! gh auth status >/dev/null 2>&1; then
      echo "Could not ask GitHub whether $branch has a PR (gh is not signed in here). If none is open, say so in your last message and name the branch." >&2
    else
      echo "Could not ask GitHub whether $branch has a PR (gh pr list failed). If none is open, open it (gh pr create --fill) or name the branch in your last message." >&2
    fi
    exit 2
  fi
  case "$open" in ''|0) ;; *) exit 0 ;; esac
  head=$(git rev-parse HEAD 2>/dev/null) || head=""
  done_heads=$(gh pr list --head "$branch" --state merged --json headRefOid --jq '.[].headRefOid' 2>/dev/null) || done_heads=""
  if [ -n "$head" ] && printf '%s\\n' "$done_heads" | grep -qx "$head"; then
    exit 0  # this exact head was merged: nothing after it
  fi
  if [ -n "$done_heads" ]; then
    echo "The PR for $branch was already merged; the commits after it are in no PR. Open a new one: gh pr create --fill, with the gate's output and what is unverified in the body." >&2
    exit 2
  fi
  closed=$(gh pr list --head "$branch" --state closed --json number --jq length 2>/dev/null) || closed=""
  case "$closed" in ''|0)
    echo "No open PR for $branch. Open it: gh pr create --fill, with the gate's output and what is unverified in the body; add --label needs-mac if a Mac-only step was skipped." >&2 ;;
  *)
    echo "The PR for $branch was closed without merging, so nothing open carries this work. Open a new one (gh pr create --fill), or say in your last message why it stays closed." >&2 ;;
  esac
  exit 2
fi
echo "gh is not available here, so the PR could not be checked. Make sure one is open for $branch, or name the branch in your last message." >&2
exit 2
"""


def rules_section() -> str:
    return "\n".join([
        START, "# In a cloud session", "",
        "These apply when `CLAUDE_CODE_REMOTE=true` (Claude Code on the web, `claude --cloud`). A local session can ignore them.", "",
        "- You can push only to this session's branch. Never try to push to the default branch: the PR is how work lands.",
        "- There is no Mac here. Never claim an Xcode build, a simulator run, a TestFlight upload, a launchd routine or a keychain step "
        "worked: say it was skipped and put the label `needs-mac` on the PR.",
        "- The owner's own instructions, skills, plugins and memory are not in this VM. AGENTS.md (section Shipping) is the policy; "
        "where an instruction points at a file in someone's home directory, follow the Shipping section instead.",
        "- Secrets exist here only as docs/cloud-setup.md says. Never ask for a key in chat, never write one into a file, never commit one.",
        "- codex and grok are not installed: a review here is a \"same-provider review\", and the PR says so.",
        "- An idle session expires and unpushed work is lost: commit and push as you go, and open the PR before you stop.",
        END]) + "\n"


# Where each kind of secret goes. HTTP APIs: the claude.ai environment's "API credentials" on
# Pro/Max (a proxy attaches them for the named host; the VM never sees the value). Apple keys:
# never in the cloud. Config that is not secret: an environment variable — which every user of
# the environment can read, so a name earns that label only from an allowlist; anything unknown
# is decided by hand (caught in review, P1: DATABASE_URL and SUPABASE_SERVICE_ROLE were "config").
_HOSTS = (("OPENAI", "api.openai.com"), ("ANTHROPIC", "api.anthropic.com"), ("XAI", "api.x.ai"),
          ("SUPABASE", "api.supabase.com / <ref>.supabase.co"), ("CLOUDFLARE", "api.cloudflare.com"),
          ("TELEGRAM", "api.telegram.org"), ("MAILGUN", "api.mailgun.net"), ("RESEND", "api.resend.com"),
          ("GITHUB", "api.github.com"), ("STRIPE", "api.stripe.com"), ("DIGITALOCEAN", "api.digitalocean.com"),
          ("STRAVA", "www.strava.com"), ("X_BEARER", "api.x.com"), ("GOOGLE", "*.googleapis.com"))
_APPLE = re.compile(r"(^|_)(ASC|APNS|APPLE|APP_STORE|P8|KEYCHAIN|SIGNING|MATCH|TESTFLIGHT)(_|$)")
_SECRET = re.compile(r"(KEY|TOKEN|SECRET|PASSWORD|PASSWD|PASS|PWD|PRIVATE|CREDENTIAL|AUTH|DSN|SERVICE_ROLE|CERT|SESSION|COOKIE|SALT|JWT|BEARER|HMAC|"
                     r"(^|_)PATS?(_|$))", re.I)  # JWT/BEARER/PAT: caught in review, P1 (VITE_GITHUB_PAT was "config")
# A connection string carries its password and is not an HTTP API a proxy can sign for.
_CONN = re.compile(r"(DSN|CONNECTION|(^|_)(DATABASE|DB|PG|POSTGRES|POSTGRESQL|MYSQL|MARIADB|MONGO|MONGODB|REDIS|"
                   r"VALKEY|KV|AMQP|RABBITMQ|RABBIT|KAFKA|NATS|MQ|BROKER|CELERY|SMTP|IMAP|FTP|SFTP|LDAP)(_|$))", re.I)
_PLAIN_EXACT = {"PORT", "HOST", "NODE_ENV", "ENV", "ENVIRONMENT", "APP_ENV", "LOG_LEVEL", "DEBUG", "TZ", "LANG", "CI"}
_PLAIN_PREFIX = ("NEXT_PUBLIC_", "VITE_", "EXPO_PUBLIC_", "REACT_APP_", "PUBLIC_")  # shipped to every browser anyway
_PLAIN_SUFFIX = ("_PORT", "_REGION", "_LOG_LEVEL", "_ENV", "_MODEL", "_TIMEOUT", "_DEBUG", "_LOCALE")


def secret_destination(name: str) -> str:
    up = name.upper()
    if _APPLE.search(up):
        return "local only: Apple keys never go to the cloud"
    if _CONN.search(up):
        return "local only: a connection string carries its password (decide by hand; never an environment variable)"
    host = next((h for k, h in _HOSTS if up.startswith(k)), None)
    if _SECRET.search(up):
        return f"API credentials, host {host}" if host else "API credentials, host: the API it is sent to (fill in)"
    if (up in _PLAIN_EXACT or up.startswith(_PLAIN_PREFIX) or up.endswith(_PLAIN_SUFFIX)
            or (host and re.fullmatch(r"[A-Z0-9]+_(BASE_)?URL", up))):
        return "environment variable (config, not a secret)"
    return "decide by hand: a secret (API credentials or local only) unless you know it is plain config"


def setup_script(repo: pathlib.Path, gate_text: str) -> list[str]:
    """Install lines for the environment setup script: uv always, then what the repo's root
    lockfiles and its gate name, then each subdirectory (depth ≤ 2) with a lockfile of its own. Every step is an `if`, never `[ -f x ] && …`: under `set -e`
    a false test as the last line would fail the whole setup."""
    has = lambda rel: (repo / rel).exists()  # noqa: E731
    L = ["#!/bin/bash", "set -euo pipefail",
         "# The directory this starts in is not documented; the repo's files are looked for there.",
         'cd "${CLAUDE_PROJECT_DIR:-$PWD}"',
         'if ! command -v uv >/dev/null 2>&1; then curl -LsSf https://astral.sh/uv/install.sh | sh; export PATH="$HOME/.local/bin:$PATH"; fi']
    if has("uv.lock"):
        L.append("if [ -f uv.lock ]; then uv sync --frozen; fi")
    elif has("pyproject.toml"):
        L.append("if [ -f pyproject.toml ]; then uv venv -q --allow-existing .venv && uv pip install -q --python .venv/bin/python -e .; fi")
    if has("requirements.txt"):
        L.append("if [ -f requirements.txt ]; then uv pip install -q --system -r requirements.txt; fi")
    if has("pnpm-lock.yaml") or re.search(r"\bpnpm\b", gate_text):
        L.append("if ! command -v pnpm >/dev/null 2>&1; then npm install -g pnpm; fi")
    if has("pnpm-lock.yaml"):
        L.append("if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile; fi")
    elif has("package-lock.json"):
        L.append("if [ -f package-lock.json ]; then npm ci; fi")
    elif has("yarn.lock"):
        L.append("if [ -f yarn.lock ]; then corepack enable && yarn install --frozen-lockfile; fi")
    elif has("package.json"):
        L.append("if [ -f package.json ]; then npm install; fi")
    if has("deno.json") or has("deno.jsonc") or has("deno.lock") or re.search(r"\bdeno\b", gate_text):
        L.append("if ! command -v deno >/dev/null 2>&1; then npm install -g deno; fi")
    sub = sub_lockfiles(repo)
    if sub and not has("pnpm-lock.yaml") and not re.search(r"\bpnpm\b", gate_text) \
            and any("pnpm-lock.yaml" in names for _, names in sub):
        L.append("if ! command -v pnpm >/dev/null 2>&1; then npm install -g pnpm; fi")
    for rel, names in sub:
        q = shlex.quote(rel)
        for lock, cmd in _SUB_INSTALL:
            if lock in names:
                L.append(f"if [ -f {shlex.quote(rel + '/' + lock)} ]; then {cmd.format(d=q)}; fi")
    for rel in swift_only_dirs(repo):
        L.append(f"# skipped on Linux: {rel} (Swift packages, Package.resolved only; a Mac resolves them)")
    return L


# Lockfiles that make a subdirectory its own install, in the order they are run. Node takes the
# first lockfile it has (a directory with two is installed once); Python lines are independent.
# Every install runs inside its directory: a requirements.txt with `-e .` run from the root
# installed the root project (caught in review, P2).
_SUB_LOCKS = ("pnpm-lock.yaml", "package-lock.json", "yarn.lock", "uv.lock", "requirements.txt")
_SUB_INSTALL = (("pnpm-lock.yaml", "(cd {d} && pnpm install --frozen-lockfile)"),
                ("package-lock.json", "(cd {d} && npm ci)"),
                ("yarn.lock", "(cd {d} && corepack enable && yarn install --frozen-lockfile)"),
                ("uv.lock", "(cd {d} && uv sync --frozen)"),
                ("requirements.txt", "(cd {d} && uv pip install -q --system -r requirements.txt)"))
_NODE_LOCKS = ("pnpm-lock.yaml", "package-lock.json", "yarn.lock")
# Never descended into: dependencies, build output, VCS and tool state, vendored trees.
_SKIP_DIRS = {"node_modules", "vendor", "vendored", "third_party", "third-party", "external", "deps", "Pods", "Carthage",
              "DerivedData", "build", "dist", "out", "target", "venv", "env", "__pycache__", "site-packages", "bower_components"}
SUB_DEPTH = 2


def _subdirs(repo: pathlib.Path):
    """Directories 1..SUB_DEPTH levels below the repo, sorted, skipping hidden, vendored and
    symlinked ones (a link could point out of the repo or back into it)."""
    def walk(d: pathlib.Path, depth: int):
        try:
            kids = sorted(p for p in d.iterdir() if p.is_dir() and not p.is_symlink())
        except OSError:
            return
        for k in kids:
            if k.name.startswith(".") or k.name in _SKIP_DIRS or k.name.endswith(".egg-info"):
                continue
            yield k
            if depth < SUB_DEPTH:
                yield from walk(k, depth + 1)
    yield from walk(repo, 1)


def sub_lockfiles(repo: pathlib.Path) -> list[tuple[str, list[str]]]:
    """(repo-relative dir, lockfiles to install from) for every subdirectory with its own
    lockfile, depth ≤ SUB_DEPTH. A web app or a worker beside the root package has its own
    dependencies, and a setup script that installs only the root leaves its gate step failing."""
    out = []
    for d in _subdirs(repo):
        found = [n for n in _SUB_LOCKS if (d / n).is_file()]
        node = next((n for n in found if n in _NODE_LOCKS), None)
        found = [n for n in found if n not in _NODE_LOCKS or n == node]
        if found:
            out.append((d.relative_to(repo).as_posix(), found))
    return out


def swift_only_dirs(repo: pathlib.Path) -> list[str]:
    """Subdirectories whose only lockfile is Package.resolved: Swift, nothing to install on Linux."""
    return [d.relative_to(repo).as_posix() for d in _subdirs(repo)
            if (d / "Package.resolved").is_file() and not any((d / n).is_file() for n in _SUB_LOCKS)]


def setup_doc(repo: pathlib.Path, names: list[str], gate: str | None, tools: list[str], gate_text: str) -> str:
    L = [START, "# Cloud setup", "",
         "What a cloud session of this repo needs that the clone does not carry. Done once, by a person, on claude.ai.", "",
         "## 1. Environment setup script", "",
         "claude.ai → Code → the environment's settings → Setup script. It runs as root on Ubuntu before the session "
         "starts and must finish in about 5 minutes to be cached. No secrets in it, and none in the environment variables: "
         "everyone who uses the environment can read them. If the dependencies do not install from here, move those lines "
         "into `.claude/hooks/teyla-cloud-start.sh` after the CLAUDE_CODE_REMOTE test.", "",
         "```bash", *setup_script(repo, gate_text), "```", "",
         "Network: \"Trusted\" (the default allowlist: package registries, GitHub, cloud SDKs) is enough for the script. "
         "Add a host under \"Custom\" only for an API the gate itself calls.", "",
         "## 2. Secrets, by name", ""]
    if names:
        L += ["From `.env.example`. Values never go into this file, the setup script, or the repo.", "",
              "- **API credentials**: claude.ai → the environment → API credentials (Pro/Max). A proxy attaches the value "
              "for the named host; the VM never sees it. Team/Enterprise plans do not have this yet: keep those steps local.",
              "- **environment variable**: the environment's variables. Every user of the environment can read them, so config only.",
              "- **local only**: stays on the Mac.",
              "- **decide by hand**: a name teyla cannot classify. Treat it as a secret until you know it is plain config.", "",
              "| name | where it goes |", "|---|---|"] + [f"| `{n}` | {secret_destination(n)} |" for n in names]
    else:
        L.append("`.env.example` names none.")
    L += ["", "## 3. The `needs-mac` label, once", "", "```bash",
          'gh label create needs-mac --color FBCA04 --description "cloud work waiting for a Mac-only step"', "```", "",
          "## What stays local", "",
          "Xcode builds, simulators, TestFlight and App Store uploads (the App Store Connect key never leaves the Mac), "
          "launchd routines, the keychain, codex/grok second opinions, deploys, and the final merge of a `needs-mac` PR."
          + (f" In this repo's gate: {', '.join(tools)}." if tools else ""),
          "", f"Gate: {('`' + gate + '`') if gate else 'none yet'}.", END]
    return "\n".join(L) + "\n"


# --- merging into what is there ----------------------------------------------------------

def replace_section(text: str, section: str) -> str:
    """Put `section` (START…END) into `text`: in place of an existing one, else at the end."""
    lines = text.splitlines(keepends=True)
    s = next((i for i, l in enumerate(lines) if l.startswith("<!-- teyla:cloud:start")), None)
    e = next((i for i, l in enumerate(lines) if s is not None and i > s and l.strip() == END), None)
    if s is not None and e is not None:
        return "".join(lines[:s]) + section + "".join(lines[e + 1:])
    if not text.strip():
        return section
    return text.rstrip("\n") + "\n\n" + section


def ensure_import(text: str) -> str:
    if re.search(r"^@AGENTS\.md\s*$", text, re.M):
        return text
    block = f"{IMPORT_START}\n@AGENTS.md\n{IMPORT_END}\n"
    return block + ("\n" + text if text.strip() else "")


def merge_settings(text: str | None) -> str:
    """.claude/settings.json with the two hooks added. Every other key is kept; an existing
    teyla-cloud entry is left as it is; a file that already has both is returned unchanged."""
    try:
        data = json.loads(text) if text and text.strip() else {}
    except ValueError as e:
        raise Refused(f".claude/settings.json is not valid JSON ({e}); fix it by hand, nothing written") from None
    if not isinstance(data, dict) or not isinstance(data.get("hooks", {}), dict):
        raise Refused(".claude/settings.json has an unexpected shape (hooks is not an object); nothing written")
    hooks = data.setdefault("hooks", {})
    changed = False
    for event, script, timeout in (("SessionStart", START_HOOK, 10), ("Stop", STOP_HOOK, 30)):
        groups = hooks.setdefault(event, [])
        if not isinstance(groups, list):
            raise Refused(f".claude/settings.json: hooks.{event} is not a list; nothing written")
        if any(script in (h.get("command") or "") for g in groups if isinstance(g, dict) for h in g.get("hooks") or [] if isinstance(h, dict)):
            continue
        groups.append({"hooks": [{"type": "command", "command": f'sh "$CLAUDE_PROJECT_DIR/{script}"', "timeout": timeout}]})
        changed = True
    if not changed and text is not None:
        return text
    return json.dumps(data, indent=2) + "\n"


def gitignore_fix(text: str) -> tuple[str, list[int]]:
    """.gitignore with each wholesale `.claude/` line replaced by the three narrow ones."""
    lines = text.splitlines()
    hit = [i for i, l in enumerate(lines) if l.strip() in _WHOLESALE]
    if not hit:
        return text, []
    keep = [l for l in GITIGNORE_LINES if l not in (x.strip() for x in lines)]
    out = []
    for i, l in enumerate(lines):
        if i == hit[0]:
            out += keep
        elif i not in hit:
            out.append(l)
    return "\n".join(out) + "\n", [i + 1 for i in hit]


# --- the privacy guard -------------------------------------------------------------------

_EMAIL = re.compile(r"[\w.+-]+@[\w-]+\.[\w.]+")


def leaks(text: str, owners: set[str] | None, slug: str | None) -> list[str]:
    out = []
    if re.search(r"(?<![\w$])~/|/Users/|/home/\w", text):
        out.append("a home-directory path")
    if _EMAIL.search(text.replace("noreply@anthropic.com", "")):
        out.append("an email address")
    others = sorted(o for o in (owners or set()) if o != (slug or "").lower() and o in text.lower())
    if others:
        out.append(f"{len(others)} other repo name(s) from the owner's list")
    return out


# --- plan, diff, write -------------------------------------------------------------------

def _inside(repo: pathlib.Path, path: pathlib.Path) -> None:
    """Refuse a destination that resolves out of the repo: a symlinked `.claude/`, settings file,
    doc or .gitignore would otherwise make prep write into someone else's tree (caught in review,
    P1). `resolve()` follows every symlinked parent and a dangling link to where it points."""
    if cloud.symlink_loop(path):
        raise Refused(f"{path.relative_to(repo) if path.is_relative_to(repo) else path.name} is a symlink loop; nothing written")
    try:
        real = path.resolve()
    except (RuntimeError, OSError):  # a loop further up the path, on Python < 3.13
        raise Refused(f"{path.name}: its path does not resolve (a symlink loop); nothing written") from None
    if real != repo and repo not in real.parents:
        try:
            rel = path.relative_to(repo)
        except ValueError:
            rel = path.name
        raise Refused(f"{rel} resolves out of the repo (a symlink); nothing written")


def _is_instruction(rel: str) -> bool:
    return rel in ("AGENTS.md", "CLAUDE.md", ".claude/CLAUDE.md") or (rel.startswith(".claude/rules/") and rel.endswith(".md"))


def _conflicting_merge_lines(repo: pathlib.Path, merge: str, changes: list) -> list[str]:
    """`file:line` of every `merge-approved:` line that disagrees with the owner's list, judged
    over each instruction file as prep would leave it — the whole file. Prep rewrites only the
    first generated section of the files it writes; any other line survives, and `teyla cloud
    check` would still report drift (caught in review, P2). Lines inside a marked section were
    skipped, so a second or unterminated section — or one in a rules file prep does not write —
    kept a stale value through prep: no section is exempt. Line numbers are those of the
    file as prep would write it."""
    pending = {(repo / rel).resolve(): new for rel, _old, new, _x in changes}
    files = {(repo / name).resolve(): (name, text) for name, text in cloud.instruction_files(repo)}
    for rel, _old, new, _x in changes:
        real = (repo / rel).resolve()
        if real not in files and _is_instruction(rel):
            files[real] = (rel, new)
    out = []
    for real, (name, text) in sorted(files.items(), key=lambda kv: kv[1][0]):
        for i, line in enumerate(pending.get(real, text).splitlines(), 1):
            m = cloud._MERGE_LINE.match(line)
            if m and m.group(1).lower() != merge:
                out.append(f"{name}:{i}")
    return out


def plan(repo, owners: set[str] | None = ..., policy_text: str | None = None, fix_gitignore: bool = False) -> dict:
    """{"changes": [(rel, old|None, new, executable)], "notes": [...]} — nothing written."""
    repo = pathlib.Path(repo).expanduser().resolve()
    if owners is ...:
        owners = cloud.owner_list()
    policy_text = owner_policy_text() if policy_text is None else policy_text
    slug = cloud.origin_slug(repo)
    merge = cloud.expected_merge_approved(slug, owners)
    notes = []
    if merge is None:
        notes.append(f"merge-approved: no ({'no GitHub origin' if slug is None else 'the owner list was not found'}); the safe default")
        merge = "no"
    gate, tools = _gate(repo)
    gate_path = cloud.gate_script(repo)
    gate_text = cloud._read(gate_path) if gate_path else ""
    changes = []
    generated = {}  # what this run authored, by file: the only text the privacy guard judges

    def put(rel_path: pathlib.Path, new: str, executable=False):
        _inside(repo, rel_path)
        old = cloud._read(rel_path) if rel_path.exists() else None
        if old != new:
            changes.append((str(rel_path.relative_to(repo)), old, new, executable))

    # AGENTS.md / CLAUDE.md
    a, c = repo / "AGENTS.md", repo / "CLAUDE.md"
    section = shipping_section(merge, gate, bool(_NO_ACTIONS.search(policy_text)))
    generated["AGENTS.md"] = section
    for p in (a, c):
        if cloud.symlink_loop(p):  # before resolve(), which raises on Python < 3.13
            raise Refused(f"{p.name} is a symlink loop; make it a real file, nothing written")
        if p.is_symlink() and repo not in p.resolve().parents:
            raise Refused(f"{p.name} is a symlink out of the repo; nothing written")
    a_real, c_real = a.resolve() if a.exists() else None, c.resolve() if c.exists() else None
    if a_real and c_real and a_real == c_real:
        put(a_real, replace_section(cloud._read(a_real), section))  # one file, two names: no import needed
    else:
        put(a_real or a, replace_section(cloud._read(a_real) if a_real else f"# {repo.name}\n", section))
        put(c_real or c, ensure_import(cloud._read(c_real) if c_real else ""))

    # .claude/
    put(repo / ".claude" / "settings.json", merge_settings(cloud._read(repo / ".claude" / "settings.json") if (repo / ".claude" / "settings.json").exists() else None))
    for rel, body in ((START_HOOK, start_hook(gate, tools, merge)), (STOP_HOOK, stop_hook(gate))):
        generated[rel] = body
        p = repo / rel
        if p.exists() and SCRIPT_HEAD not in cloud._read(p):
            notes.append(f"{rel} exists and is hand-written: not touched")
            continue
        put(p, body, executable=True)
    rules = repo / ".claude" / "rules" / "cloud.md"
    generated["rules"] = rules_section()
    put(rules, replace_section(cloud._read(rules) if rules.exists() else "", generated["rules"]))

    # docs/cloud-setup.md
    doc = repo / cloud.SECRETS_MANIFEST
    generated["doc"] = setup_doc(repo, cloud.env_example_names(repo), gate, tools, gate_text)
    put(doc, replace_section(cloud._read(doc) if doc.exists() else "", generated["doc"]))

    # .gitignore
    ignored = cloud.claude_ignored(repo)
    if ignored:
        gi = repo / ".gitignore"
        new, hit = gitignore_fix(cloud._read(gi)) if gi.exists() else ("", [])
        if not hit:
            notes.append(f"{', '.join(ignored)} git-ignored by a rule outside .gitignore's plain `.claude/` lines "
                         "(a nested or global ignore): fix it by hand, or the files above cannot be committed")
        elif fix_gitignore:
            put(gi, new)
        else:
            notes.append(f".gitignore ignores .claude/ wholesale (line {', '.join(map(str, hit))}), so the files above cannot be "
                         "committed. Replace that line with:\n    " + "\n    ".join(GITIGNORE_LINES)
                         + "\n  (re-run with --fix-gitignore to apply)")

    conflicts = _conflicting_merge_lines(repo, merge, changes)
    if conflicts:
        raise Refused(f"merge-approved: {merge} is what the owner's list says, but {', '.join(conflicts)} says otherwise "
                      "outside what prep rewrites; fix those lines by hand, nothing written")

    generated["settings"] = merge_settings(None) + ensure_import("")
    for name, text in generated.items():
        found = leaks(text, owners, slug)
        if found:
            raise Refused(f"{name}: the generated text would contain {', '.join(found)}; nothing written (a bug — report it)")
    return {"repo": repo, "slug": slug, "merge": merge, "changes": changes, "notes": notes}


def diff(p: dict) -> str:
    out = []
    for rel, old, new, _ in p["changes"]:
        out += difflib.unified_diff((old or "").splitlines(keepends=True), new.splitlines(keepends=True),
                                    fromfile="/dev/null" if old is None else f"a/{rel}", tofile=f"b/{rel}", n=0)
        if out and not out[-1].endswith("\n"):
            out[-1] += "\n"
    return "".join(out)


def apply(p: dict) -> list[str]:
    for rel, *_ in p["changes"]:  # again, all before the first write: the tree may have moved since plan()
        _inside(p["repo"], p["repo"] / rel)
    done = []
    for rel, old, new, executable in p["changes"]:
        f = p["repo"] / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(new)
        if executable:
            f.chmod(0o755)
        done.append(f"{'wrote' if old is None else 'updated'} {rel}")
    return done


def prep(repo, dry=False, allow_public=False, fix_gitignore=False, owners=..., policy_text=None, vis=...) -> tuple[int, list[str]]:
    repo = pathlib.Path(repo).expanduser().resolve()
    if not (repo / ".git").exists():
        return 1, [f"{repo.name}: not a git repo"]
    try:
        p = plan(repo, owners=owners, policy_text=policy_text, fix_gitignore=fix_gitignore)
    except Refused as e:
        return 1, [f"refused: {e}"]
    head = f"{repo.name}: merge-approved: {p['merge']}; {len(p['changes'])} file(s) to change"
    out = [head] + [f"note: {n}" for n in p["notes"]]
    if not p["changes"]:
        return 0, out + ["up to date: nothing to write"]
    if dry:
        return 0, out + ["", diff(p).rstrip("\n")]
    if vis is ...:
        vis = cloud.visibility(p["slug"])
    if vis not in ("private", "internal") and not allow_public:
        return 1, out + [f"refused: {repo.name} is {'public' if vis == 'public' else 'of unknown visibility (no gh, safe mode, or no GitHub origin), so treated as public'}. "
                         "These files carry the shipping policy and the merge-approved flag: re-run with --allow-public "
                         "to write them anyway, or --dry to read them first"]
    try:
        out += apply(p)
    except Refused as e:
        return 1, out + [f"refused: {e}"]
    out += ["", "next: commit these on a branch and open the PR; paste docs/cloud-setup.md §1 into the claude.ai environment; "
                "create the needs-mac label once (§3)"]
    return 0, out


def cmd_prep(args) -> int:
    if not args.paths or len(args.paths) != 1:
        print("usage: teyla cloud prep <repo> [--dry] [--allow-public] [--fix-gitignore]")
        return 2
    rc, lines = prep(args.paths[0], dry=args.dry, allow_public=args.allow_public, fix_gitignore=args.fix_gitignore)
    print("\n".join(lines))
    return rc
