"""`teyla cloud prep <repo> [--dry] [--allow-public] [--fix-gitignore]` — put into a repo's
working tree what a cloud session needs to finish, as plain files (a cloud VM installs no
plugins, not even ones the repo's settings declare):

    AGENTS.md                  a Shipping section between <!-- teyla:cloud:start/end -->: the
                               repo-safe part of the owner's policy, `merge-approved: yes|no`
                               from the owner's list, and the cloud definition of done
    CLAUDE.md                  `@AGENTS.md` at the top, inside markers, when CLAUDE.md is its
                               own file (a CLAUDE.md ⇄ AGENTS.md symlink needs nothing)
    .claude/settings.json      SessionStart + Stop hooks, merged into what is there
    .claude/hooks/teyla-cloud-start.sh   orientation, printed only when CLAUDE_CODE_REMOTE=true
    .claude/hooks/teyla-cloud-stop.sh    exit 2 while work is unpushed or has no PR (cloud only)
    .claude/rules/cloud.md     the rules that only apply in a cloud VM
    docs/cloud-setup.md        the setup script to paste into claude.ai, and the secret NAMES
                               from .env.example with where each goes
    .gitignore                 only with --fix-gitignore: `.claude/` wholesale → three lines

Idempotent: markdown goes between markers and everything outside them is left alone; a
script or rules file that exists without the generated header is hand-written and skipped.
`--dry` prints a unified diff of every file (no context lines: the output is meant to be
pasteable, and context would quote the repo's own text).

Everything written here may end up public, so the content is generic by construction and
checked before any write: no home-directory path, no email, no other repo from the owner's
list. A repo that is public — or whose visibility cannot be asked, which counts as public — is
refused unless --allow-public.
"""
from __future__ import annotations

import difflib
import json
import os
import pathlib
import re

from . import cloud

START = "<!-- teyla:cloud:start — generated by `teyla cloud prep`; re-run it to refresh, edit outside these markers -->"
END = "<!-- teyla:cloud:end -->"
IMPORT_START = "<!-- teyla:cloud-import:start -->"
IMPORT_END = "<!-- teyla:cloud-import:end -->"
SCRIPT_HEAD = "# Generated by `teyla cloud prep` — re-run it to refresh; edits here are overwritten."
START_HOOK = ".claude/hooks/teyla-cloud-start.sh"
STOP_HOOK = ".claude/hooks/teyla-cloud-stop.sh"
GITIGNORE_LINES = (".claude/settings.local.json", ".claude/launch.json", ".claude/worktrees/")
_WHOLESALE = {".claude", ".claude/", "/.claude", "/.claude/", ".claude/*", "/.claude/*", ".claude/**", "/.claude/**"}

_NO_ACTIONS = re.compile(r"No GitHub Actions|GitHub Actions are off", re.I)


class Refused(Exception):
    pass


# --- inputs ------------------------------------------------------------------------------

def owner_policy_text() -> str:
    """The owner's policy files, read only to decide which generic rules apply (today: whether
    GitHub Actions are off). Nothing from them is copied."""
    home = pathlib.Path.home()
    return "\n".join(cloud._read(p) for p in (home / ".claude" / "CLAUDE.md", home / ".agents" / "POLICY.md"))


def _gate(repo: pathlib.Path) -> tuple[str | None, list[str]]:
    g = cloud.gate_script(repo)
    if g is None:
        return None, []
    return "./" + str(g.relative_to(repo)), sorted({s["tool"] for s in cloud.mac_steps(cloud._read(g))})


# --- the generated content ---------------------------------------------------------------

def shipping_section(merge: str, gate: str | None, no_actions: bool) -> str:
    g = f"`{gate}`" if gate else "the repo's tests"
    L = [START, "## Shipping", "", f"merge-approved: {merge}", "",
         "- One PR per logical unit: what a reviewer reads in one sitting. Two unrelated fixes are two PRs.",
         "- Merge, don't squash (`gh pr merge --merge`): every commit stays in history.",
         "- Never force-push: not to the default branch, not to a shared branch.",
         ]
    if no_actions:
        L.append(f"- No GitHub Actions on push or pull_request. The gate is {g}, run before every push.")
    L += ["- Report honestly: what you could not verify goes in the same sentence as the claim.",
          "- Ask about product decisions with a proposed default; never ask for permission to proceed.",
          ("- This repo is merge-approved: a PR whose whole gate ran green may be merged without asking."
           if merge == "yes" else "- This repo is not merge-approved: open the PR and stop; the owner merges."),
          "", "### Done, in a cloud session", "",
          "A cloud session (`CLAUDE_CODE_REMOTE=true`) can push only to its own branch and has no Mac. It is done when:", "",
          f"1. {g} ran here and the PR body carries its output: the result, and every line saying what was skipped.",
          "2. The branch is pushed and a PR is open (`gh pr create --fill`, then a body: what changed, why, the gate output, what is unverified).",
          "3. A step that needs a Mac (Xcode, simulator, TestFlight, launchd, keychain) and was skipped puts the label `needs-mac` on the PR "
          "(`gh pr edit --add-label needs-mac`). That PR is not merged from the cloud: a local session builds, reviews and merges it.",
          "4. Second opinion: codex and grok are not installed here. Review the diff in a fresh pass and call it a \"same-provider review\" in the PR body.",
          ]
    if merge == "yes":
        L.append("5. Nothing skipped and the gate green: merge it (`gh pr merge --merge`). If merging is refused from here, the open PR is the done state.")
    L += [END]
    return "\n".join(L) + "\n"


def start_hook(gate: str | None, tools: list[str], merge: str) -> str:
    skips = ", ".join(tools) if tools else "nothing in the gate needs a Mac"
    gate_line = f"Gate: {gate} (run it before every push; its output goes in the PR body)" if gate else \
        "Gate: none in this repo; run the tests you can find and say which ran"
    return f"""#!/bin/sh
{SCRIPT_HEAD}
# SessionStart: orientation for a cloud session. Silent anywhere else: CLAUDE_CODE_REMOTE is
# "true" only on a cloud VM, and stdout of this hook reaches the model there.
[ "${{CLAUDE_CODE_REMOTE:-}}" = "true" ] || exit 0
cd "${{CLAUDE_PROJECT_DIR:-.}}" 2>/dev/null || exit 0
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "?")
cat <<EOF
Cloud session on branch $branch. This VM has the repository only: no Mac, and nothing from the owner's machine.
{gate_line}
Skipped here without a Mac: {skips}
merge-approved: {merge} (AGENTS.md, section Shipping)
Before you stop: push this branch and open the PR (gh pr create --fill); label it needs-mac if a Mac-only step was skipped. The Stop hook checks for the PR.
EOF
"""


def stop_hook(gate: str | None) -> str:
    g = gate or "the tests"
    return f"""#!/bin/sh
{SCRIPT_HEAD}
# Stop: in a cloud session, do not stop while this branch's work is uncommitted, unpushed, or
# has no PR. Exit 2 hands the message back to the model. A second stop in a row goes through
# (stop_hook_active), so a session that cannot push is told once, never trapped.
[ "${{CLAUDE_CODE_REMOTE:-}}" = "true" ] || exit 0
input=$(cat)
case "$input" in *'"stop_hook_active":true'*|*'"stop_hook_active": true'*) exit 0 ;; esac
cd "${{CLAUDE_PROJECT_DIR:-.}}" 2>/dev/null || exit 0
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null) || exit 0
[ "$branch" = "HEAD" ] && exit 0
base=$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null || echo origin/main)
[ "$branch" = "${{base#origin/}}" ] && exit 0
if [ -n "$(git status --porcelain 2>/dev/null | head -1)" ]; then
  echo "Uncommitted changes on $branch: run {g}, commit, push, and open the PR before you stop." >&2
  exit 2
fi
ahead=$(git rev-list --count "$base..HEAD" 2>/dev/null || echo 0)
[ "$ahead" = 0 ] && exit 0
if git rev-parse --abbrev-ref --symbolic-full-name '@{{u}}' >/dev/null 2>&1; then
  unpushed=$(git rev-list --count '@{{u}}..HEAD' 2>/dev/null || echo "$ahead")
else
  unpushed=$ahead
fi
if [ "$unpushed" != 0 ]; then
  echo "$unpushed commit(s) on $branch are not on the remote: git push -u origin $branch, then open the PR (gh pr create --fill) before you stop." >&2
  exit 2
fi
if command -v gh >/dev/null 2>&1; then
  state=$(gh pr view "$branch" --json state --jq .state 2>/dev/null) || state=""
  case "$state" in OPEN|MERGED) exit 0 ;; esac
  if [ -z "$state" ] && ! gh auth status >/dev/null 2>&1; then
    echo "Could not ask GitHub whether $branch has a PR (gh is not signed in here). If none is open, say so in your last message and name the branch." >&2
    exit 2
  fi
  echo "No open PR for $branch. Open it: gh pr create --fill, with the gate's output and what is unverified in the body; add --label needs-mac if a Mac-only step was skipped." >&2
  exit 2
fi
echo "gh is not available here, so the PR could not be checked. Make sure one is open for $branch, or name the branch in your last message." >&2
exit 2
"""


def rules_section() -> str:
    return "\n".join([
        START, "# In a cloud session", "",
        "These apply when `CLAUDE_CODE_REMOTE=true` (Claude Code on the web, `claude --cloud`). A local session can ignore them.", "",
        "- You can push only to this session's branch. Never try to push to the default branch: the PR is how work lands.",
        "- There is no Mac here. Never claim an Xcode build, a simulator run, a TestFlight upload, a launchd routine or a keychain step "
        "worked: say it was skipped and put the label `needs-mac` on the PR.",
        "- The owner's own instructions, skills, plugins and memory are not in this VM. AGENTS.md (section Shipping) is the policy; "
        "where an instruction points at a file in someone's home directory, follow the Shipping section instead.",
        "- Secrets exist here only as docs/cloud-setup.md says. Never ask for a key in chat, never write one into a file, never commit one.",
        "- codex and grok are not installed: a review here is a \"same-provider review\", and the PR says so.",
        "- An idle session expires and unpushed work is lost: commit and push as you go, and open the PR before you stop.",
        END]) + "\n"


# Where each kind of secret goes. HTTP APIs: the claude.ai environment's "API credentials" on
# Pro/Max (a proxy attaches them for the named host; the VM never sees the value). Apple keys:
# never in the cloud. Config that is not secret: an environment variable.
_HOSTS = (("OPENAI", "api.openai.com"), ("ANTHROPIC", "api.anthropic.com"), ("XAI", "api.x.ai"),
          ("SUPABASE", "api.supabase.com / <ref>.supabase.co"), ("CLOUDFLARE", "api.cloudflare.com"),
          ("TELEGRAM", "api.telegram.org"), ("MAILGUN", "api.mailgun.net"), ("RESEND", "api.resend.com"),
          ("GITHUB", "api.github.com"), ("STRIPE", "api.stripe.com"), ("DIGITALOCEAN", "api.digitalocean.com"),
          ("STRAVA", "www.strava.com"), ("X_BEARER", "api.x.com"), ("GOOGLE", "*.googleapis.com"))
_APPLE = re.compile(r"(^|_)(ASC|APNS|APPLE|APP_STORE|P8|KEYCHAIN|SIGNING|MATCH|TESTFLIGHT)(_|$)")
_SECRET = re.compile(r"(KEY|TOKEN|SECRET|PASSWORD|PASS|PRIVATE|CREDENTIAL|AUTH)", re.I)


def secret_destination(name: str) -> str:
    if _APPLE.search(name.upper()):
        return "local only: Apple keys never go to the cloud"
    if not _SECRET.search(name):
        return "environment variable (config, not a secret)"
    host = next((h for k, h in _HOSTS if name.upper().startswith(k)), None)
    return f"API credentials, host {host}" if host else "API credentials, host: the API it is sent to (fill in)"


def setup_script(repo: pathlib.Path, gate_text: str) -> list[str]:
    """Install lines for the environment setup script: uv always, then what the repo's root
    lockfiles and its gate name. Every step is an `if`, never `[ -f x ] && …`: under `set -e`
    a false test as the last line would fail the whole setup."""
    has = lambda rel: (repo / rel).exists()  # noqa: E731
    L = ["#!/bin/bash", "set -euo pipefail",
         "# The directory this starts in is not documented; the repo's files are looked for there.",
         'cd "${CLAUDE_PROJECT_DIR:-$PWD}"',
         'if ! command -v uv >/dev/null 2>&1; then curl -LsSf https://astral.sh/uv/install.sh | sh; export PATH="$HOME/.local/bin:$PATH"; fi']
    if has("uv.lock"):
        L.append("if [ -f uv.lock ]; then uv sync --frozen; fi")
    elif has("pyproject.toml"):
        L.append("if [ -f pyproject.toml ]; then uv venv -q --allow-existing .venv && uv pip install -q --python .venv/bin/python -e .; fi")
    if has("requirements.txt"):
        L.append("if [ -f requirements.txt ]; then uv pip install -q --system -r requirements.txt; fi")
    if has("pnpm-lock.yaml") or re.search(r"\bpnpm\b", gate_text):
        L.append("if ! command -v pnpm >/dev/null 2>&1; then npm install -g pnpm; fi")
    if has("pnpm-lock.yaml"):
        L.append("if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile; fi")
    elif has("package-lock.json"):
        L.append("if [ -f package-lock.json ]; then npm ci; fi")
    elif has("yarn.lock"):
        L.append("if [ -f yarn.lock ]; then corepack enable && yarn install --frozen-lockfile; fi")
    elif has("package.json"):
        L.append("if [ -f package.json ]; then npm install; fi")
    if has("deno.json") or has("deno.jsonc") or has("deno.lock") or re.search(r"\bdeno\b", gate_text):
        L.append("if ! command -v deno >/dev/null 2>&1; then npm install -g deno; fi")
    return L


def setup_doc(repo: pathlib.Path, names: list[str], gate: str | None, tools: list[str], gate_text: str) -> str:
    L = [START, "# Cloud setup", "",
         "What a cloud session of this repo needs that the clone does not carry. Done once, by a person, on claude.ai.", "",
         "## 1. Environment setup script", "",
         "claude.ai → Code → the environment's settings → Setup script. It runs as root on Ubuntu before the session "
         "starts and must finish in about 5 minutes to be cached. No secrets in it, and none in the environment variables: "
         "everyone who uses the environment can read them. If the dependencies do not install from here, move those lines "
         "into `.claude/hooks/teyla-cloud-start.sh` after the CLAUDE_CODE_REMOTE test.", "",
         "```bash", *setup_script(repo, gate_text), "```", "",
         "Network: \"Trusted\" (the default allowlist: package registries, GitHub, cloud SDKs) is enough for the script. "
         "Add a host under \"Custom\" only for an API the gate itself calls.", "",
         "## 2. Secrets, by name", ""]
    if names:
        L += ["From `.env.example`. Values never go into this file, the setup script, or the repo.", "",
              "- **API credentials**: claude.ai → the environment → API credentials (Pro/Max). A proxy attaches the value "
              "for the named host; the VM never sees it. Team/Enterprise plans do not have this yet: keep those steps local.",
              "- **environment variable**: the environment's variables. Every user of the environment can read them, so config only.",
              "- **local only**: stays on the Mac.", "",
              "| name | where it goes |", "|---|---|"] + [f"| `{n}` | {secret_destination(n)} |" for n in names]
    else:
        L.append("`.env.example` names none.")
    L += ["", "## 3. The `needs-mac` label, once", "", "```bash",
          'gh label create needs-mac --color FBCA04 --description "cloud work waiting for a Mac-only step"', "```", "",
          "## What stays local", "",
          "Xcode builds, simulators, TestFlight and App Store uploads (the App Store Connect key never leaves the Mac), "
          "launchd routines, the keychain, codex/grok second opinions, deploys, and the final merge of a `needs-mac` PR."
          + (f" In this repo's gate: {', '.join(tools)}." if tools else ""),
          "", f"Gate: {('`' + gate + '`') if gate else 'none yet'}.", END]
    return "\n".join(L) + "\n"


# --- merging into what is there ----------------------------------------------------------

def replace_section(text: str, section: str) -> str:
    """Put `section` (START…END) into `text`: in place of an existing one, else at the end."""
    lines = text.splitlines(keepends=True)
    s = next((i for i, l in enumerate(lines) if l.startswith("<!-- teyla:cloud:start")), None)
    e = next((i for i, l in enumerate(lines) if s is not None and i > s and l.strip() == END), None)
    if s is not None and e is not None:
        return "".join(lines[:s]) + section + "".join(lines[e + 1:])
    if not text.strip():
        return section
    return text.rstrip("\n") + "\n\n" + section


def ensure_import(text: str) -> str:
    if re.search(r"^@AGENTS\.md\s*$", text, re.M):
        return text
    block = f"{IMPORT_START}\n@AGENTS.md\n{IMPORT_END}\n"
    return block + ("\n" + text if text.strip() else "")


def merge_settings(text: str | None) -> str:
    """.claude/settings.json with the two hooks added. Every other key is kept; an existing
    teyla-cloud entry is left as it is; a file that already has both is returned unchanged."""
    try:
        data = json.loads(text) if text and text.strip() else {}
    except ValueError as e:
        raise Refused(f".claude/settings.json is not valid JSON ({e}); fix it by hand, nothing written") from None
    if not isinstance(data, dict) or not isinstance(data.get("hooks", {}), dict):
        raise Refused(".claude/settings.json has an unexpected shape (hooks is not an object); nothing written")
    hooks = data.setdefault("hooks", {})
    changed = False
    for event, script, timeout in (("SessionStart", START_HOOK, 10), ("Stop", STOP_HOOK, 30)):
        groups = hooks.setdefault(event, [])
        if not isinstance(groups, list):
            raise Refused(f".claude/settings.json: hooks.{event} is not a list; nothing written")
        if any(script in (h.get("command") or "") for g in groups if isinstance(g, dict) for h in g.get("hooks") or [] if isinstance(h, dict)):
            continue
        groups.append({"hooks": [{"type": "command", "command": f'sh "$CLAUDE_PROJECT_DIR/{script}"', "timeout": timeout}]})
        changed = True
    if not changed and text is not None:
        return text
    return json.dumps(data, indent=2) + "\n"


def gitignore_fix(text: str) -> tuple[str, list[int]]:
    """.gitignore with each wholesale `.claude/` line replaced by the three narrow ones."""
    lines = text.splitlines()
    hit = [i for i, l in enumerate(lines) if l.strip() in _WHOLESALE]
    if not hit:
        return text, []
    keep = [l for l in GITIGNORE_LINES if l not in (x.strip() for x in lines)]
    out = []
    for i, l in enumerate(lines):
        if i == hit[0]:
            out += keep
        elif i not in hit:
            out.append(l)
    return "\n".join(out) + "\n", [i + 1 for i in hit]


# --- the privacy guard -------------------------------------------------------------------

_EMAIL = re.compile(r"[\w.+-]+@[\w-]+\.[\w.]+")


def leaks(text: str, owners: set[str] | None, slug: str | None) -> list[str]:
    out = []
    if re.search(r"(?<![\w$])~/|/Users/|/home/\w", text):
        out.append("a home-directory path")
    if _EMAIL.search(text.replace("noreply@anthropic.com", "")):
        out.append("an email address")
    others = sorted(o for o in (owners or set()) if o != (slug or "").lower() and o in text.lower())
    if others:
        out.append(f"{len(others)} other repo name(s) from the owner's list")
    return out


# --- plan, diff, write -------------------------------------------------------------------

def plan(repo, owners: set[str] | None = ..., policy_text: str | None = None, fix_gitignore: bool = False) -> dict:
    """{"changes": [(rel, old|None, new, executable)], "notes": [...]} — nothing written."""
    repo = pathlib.Path(repo).expanduser().resolve()
    if owners is ...:
        owners = cloud.owner_list()
    policy_text = owner_policy_text() if policy_text is None else policy_text
    slug = cloud.origin_slug(repo)
    merge = cloud.expected_merge_approved(slug, owners)
    notes = []
    if merge is None:
        notes.append(f"merge-approved: no ({'no GitHub origin' if slug is None else 'the owner list was not found'}); the safe default")
        merge = "no"
    gate, tools = _gate(repo)
    gate_path = cloud.gate_script(repo)
    gate_text = cloud._read(gate_path) if gate_path else ""
    changes = []
    generated = {}  # what this run authored, by file: the only text the privacy guard judges

    def put(rel_path: pathlib.Path, new: str, executable=False):
        old = cloud._read(rel_path) if rel_path.exists() else None
        if old != new:
            changes.append((str(rel_path.relative_to(repo)), old, new, executable))

    # AGENTS.md / CLAUDE.md
    a, c = repo / "AGENTS.md", repo / "CLAUDE.md"
    section = shipping_section(merge, gate, bool(_NO_ACTIONS.search(policy_text)))
    generated["AGENTS.md"] = section
    for p in (a, c):
        if p.is_symlink() and repo not in p.resolve().parents:
            raise Refused(f"{p.name} is a symlink out of the repo; nothing written")
    a_real, c_real = a.resolve() if a.exists() else None, c.resolve() if c.exists() else None
    if a_real and c_real and a_real == c_real:
        put(a_real, replace_section(cloud._read(a_real), section))  # one file, two names: no import needed
    else:
        put(a_real or a, replace_section(cloud._read(a_real) if a_real else f"# {repo.name}\n", section))
        put(c_real or c, ensure_import(cloud._read(c_real) if c_real else ""))

    # .claude/
    put(repo / ".claude" / "settings.json", merge_settings(cloud._read(repo / ".claude" / "settings.json") if (repo / ".claude" / "settings.json").exists() else None))
    for rel, body in ((START_HOOK, start_hook(gate, tools, merge)), (STOP_HOOK, stop_hook(gate))):
        generated[rel] = body
        p = repo / rel
        if p.exists() and SCRIPT_HEAD not in cloud._read(p):
            notes.append(f"{rel} exists and is hand-written: not touched")
            continue
        put(p, body, executable=True)
    rules = repo / ".claude" / "rules" / "cloud.md"
    generated["rules"] = rules_section()
    put(rules, replace_section(cloud._read(rules) if rules.exists() else "", generated["rules"]))

    # docs/cloud-setup.md
    doc = repo / cloud.SECRETS_MANIFEST
    generated["doc"] = setup_doc(repo, cloud.env_example_names(repo), gate, tools, gate_text)
    put(doc, replace_section(cloud._read(doc) if doc.exists() else "", generated["doc"]))

    # .gitignore
    ignored = cloud.claude_ignored(repo)
    if ignored:
        gi = repo / ".gitignore"
        new, hit = gitignore_fix(cloud._read(gi)) if gi.exists() else ("", [])
        if not hit:
            notes.append(f"{', '.join(ignored)} git-ignored by a rule outside .gitignore's plain `.claude/` lines "
                         "(a nested or global ignore): fix it by hand, or the files above cannot be committed")
        elif fix_gitignore:
            put(gi, new)
        else:
            notes.append(f".gitignore ignores .claude/ wholesale (line {', '.join(map(str, hit))}), so the files above cannot be "
                         "committed. Replace that line with:\n    " + "\n    ".join(GITIGNORE_LINES)
                         + "\n  (re-run with --fix-gitignore to apply)")

    generated["settings"] = merge_settings(None) + ensure_import("")
    for name, text in generated.items():
        found = leaks(text, owners, slug)
        if found:
            raise Refused(f"{name}: the generated text would contain {', '.join(found)}; nothing written (a bug — report it)")
    return {"repo": repo, "slug": slug, "merge": merge, "changes": changes, "notes": notes}


def diff(p: dict) -> str:
    out = []
    for rel, old, new, _ in p["changes"]:
        out += difflib.unified_diff((old or "").splitlines(keepends=True), new.splitlines(keepends=True),
                                    fromfile="/dev/null" if old is None else f"a/{rel}", tofile=f"b/{rel}", n=0)
        if out and not out[-1].endswith("\n"):
            out[-1] += "\n"
    return "".join(out)


def apply(p: dict) -> list[str]:
    done = []
    for rel, old, new, executable in p["changes"]:
        f = p["repo"] / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(new)
        if executable:
            f.chmod(0o755)
        done.append(f"{'wrote' if old is None else 'updated'} {rel}")
    return done


def prep(repo, dry=False, allow_public=False, fix_gitignore=False, owners=..., policy_text=None, vis=...) -> tuple[int, list[str]]:
    repo = pathlib.Path(repo).expanduser().resolve()
    if not (repo / ".git").exists():
        return 1, [f"{repo.name}: not a git repo"]
    try:
        p = plan(repo, owners=owners, policy_text=policy_text, fix_gitignore=fix_gitignore)
    except Refused as e:
        return 1, [f"refused: {e}"]
    head = f"{repo.name}: merge-approved: {p['merge']}; {len(p['changes'])} file(s) to change"
    out = [head] + [f"note: {n}" for n in p["notes"]]
    if not p["changes"]:
        return 0, out + ["up to date: nothing to write"]
    if dry:
        return 0, out + ["", diff(p).rstrip("\n")]
    if vis is ...:
        vis = cloud.visibility(p["slug"])
    if vis not in ("private", "internal") and not allow_public:
        return 1, out + [f"refused: {repo.name} is {'public' if vis == 'public' else 'of unknown visibility (no gh, safe mode, or no GitHub origin), so treated as public'}. "
                         "These files carry the shipping policy and the merge-approved flag: re-run with --allow-public "
                         "to write them anyway, or --dry to read them first"]
    out += apply(p)
    out += ["", "next: commit these on a branch and open the PR; paste docs/cloud-setup.md §1 into the claude.ai environment; "
                "create the needs-mac label once (§3)"]
    return 0, out


def cmd_prep(args) -> int:
    if not args.paths or len(args.paths) != 1:
        print("usage: teyla cloud prep <repo> [--dry] [--allow-public] [--fix-gitignore]")
        return 2
    rc, lines = prep(args.paths[0], dry=args.dry, allow_public=args.allow_public, fix_gitignore=args.fix_gitignore)
    print("\n".join(lines))
    return rc
