"""`teyla tidy` — find the junk that piles up in governance markdown, and fix only the safe part.

The files: the owner's global rules (`~/.agents/POLICY.md`, `~/.claude/CLAUDE.md`), the shared
memory (`~/.claude/projects/*/memory/*.md` and each `MEMORY.md` index), and per repo `CLAUDE.md`,
`AGENTS.md` and `.claude/rules/*.md`. They grow dated anecdotes, copies of each other's lines and
pointers to files that moved. Teyla finds that deterministically (no model) and never rewrites
prose a person wrote: the editorial pass (shorten, merge, move) is the `tidy` skill, which proposes
a diff and asks.

    teyla tidy [paths...] [--json] [--quiet]     read-only report, file:line + a fix for each finding
    teyla tidy [paths...] --apply                the mechanical fixes only, backup first

Findings (rule id: what):
    dup-line         exact duplicate line or bullet (whitespace ignored) in a file; across POLICY.md and CLAUDE.md
    near-dup         bullets >= 40 chars with difflib ratio >= 0.9
    broken-import    `@path` import whose file is missing
    broken-link      markdown link to a local file that is missing
    broken-memory-link  `[[name]]` in a memory file with no such memory
    memory-index     MEMORY.md line pointing at a missing file
    memory-unlisted  memory file that MEMORY.md does not list
    memory-frontmatter  memory file without name, description or type
    size             file over `tidy.max_kb` (default 24); MEMORY.md index line over 200 chars
    trailing-ws, blank-run, tab-list   whitespace
    non-english      Cyrillic prose in a file inside a git repo (everything in a repo is English)
    stale-date       a date older than `tidy.stale_days` (default 120) on a line that says until,
                     for now, temporary, this week or TODO

Only trailing-ws, blank-run, tab-list and a dup-line whose later copy is a single bullet are
applied. Everything else is report-only.

Protected, never touched and never reported on: a fenced code block, the region between
`<!-- teyla:protect -->` and `<!-- /teyla:protect -->`, and the regions Teyla itself generates
(`teyla:cloud`, `teyla:cloud-import`, `ladder`). A fenced block whose first line holds
MERGE-APPROVED (the owner's merge-approved repo list) is one of these: it stays byte-identical
whatever its indentation, fence character or missing closing fence. After computing a fix, `apply` re-reads its own output and
refuses to write a file whose protected lines are not byte-identical to the original.

`--apply` also refuses a symlink, a file `teyla policy sync` or `harness sync` generated, a file
that changed while it ran, and any file it could not back up first
(`~/.teyla/tidy-backup/<date-time>/<flattened path>`).
"""
from __future__ import annotations

import datetime as _dt
import difflib
import json
import os
import pathlib
import re
import sys
import tempfile

PROTECT_START = "<!-- teyla:protect -->"
PROTECT_END = "<!-- /teyla:protect -->"
# Regions another Teyla command writes and refreshes: editing inside them is pointless.
_MANAGED = (
    (re.compile(r"<!--\s*teyla:cloud:start\b"), re.compile(r"<!--\s*teyla:cloud:end\b")),
    (re.compile(r"<!--\s*teyla:cloud-import:start\b"), re.compile(r"<!--\s*teyla:cloud-import:end\b")),
    (re.compile(r"<!--\s*ladder:start\b"), re.compile(r"<!--\s*ladder:end\b")),
)
_GENERATED = ("<!-- generated by teyla policy sync", "<!-- generated by `teyla policy sync`",
              "<!-- generated by `teyla harness sync`")

DEFAULT_MAX_KB = 24
DEFAULT_STALE_DAYS = 120
INDEX_LINE_MAX = 200
DUP_MIN = 20       # a list item shorter than this is not worth a duplicate finding
PARA_MIN = 30      # ... nor a plain paragraph line
NEAR_MIN = 40
NEAR_RATIO = 0.9
STALE_WORDS = re.compile(r"\b(?:until|for now|temporary|this week|todo)\b", re.I)
DATE_RE = re.compile(r"\b(\d{4})-(\d{2})-(\d{2})\b")
CYRILLIC = re.compile(r"[\u0400-\u04FF]")  # as in scripts/leak_check.py: U+0400-U+04FF

FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})(.*)$")
_QUOTE_RE = re.compile(r"^(?:\s*>)+")  # a fence may sit inside a blockquote: `> ```


def _quote_depth(line: str) -> tuple[int, str]:
    """(blockquote depth, the line without its `>` markers)."""
    m = _QUOTE_RE.match(line)
    return (m.group(0).count(">"), line[m.end():]) if m else (0, line)
LIST_RE = re.compile(r"^(\s*)([-*+]|\d+[.)])\s+(\S.*)$")
BULLET_RE = re.compile(r"^(\s*)[-*+]\s+(\S.*)$")
HEADING_RE = re.compile(r"^\s{0,3}#{1,6}(\s|$)")
HR_RE = re.compile(r"^\s*([-*_])(\s*\1){2,}\s*$")
LINK_RE = re.compile(r"!?\[[^\]\n]*\]\(\s*(<[^>\n]+>|[^)\s]+)(?:\s+(?:\"[^\"]*\"|'[^']*'))?\s*\)")
MEMLINK_RE = re.compile(r"\[\[([^\[\]\n|#]+)(?:[|#][^\[\]\n]*)?\]\]")
CODE_SPAN_RE = re.compile(r"`[^`\n]*`")
_URL_RE = re.compile(r"^[A-Za-z][A-Za-z0-9+.\-]*:")
_PREFIXED_PATH = re.compile(r"(?:~|\.{1,2})?/[\w.\-/+@]*")
# A bare `@name.ext` is an import only for a document-ish extension (`@in.example.ai` is a domain).
_BARE_PATH = re.compile(r"[\w.\-]+(?:/[\w.\-]+)*\.(?:md|mdc|txt|json|ya?ml|toml|sh)|[\w.\-]+/[\w.\-/]*\.[A-Za-z0-9]{1,5}")
_LABEL_RE = re.compile(r"^(\*\*|__|\*|_)[^*_]+\1:?$")


# --- environment, read at call time so a test's HOME and TEYLA_HOME are honoured ---------------

def _home() -> pathlib.Path:
    return pathlib.Path.home()


def _teyla_dir() -> pathlib.Path:
    return pathlib.Path(os.environ.get("TEYLA_HOME") or (_home() / ".teyla")).expanduser()


def settings(cfg: dict | None = None) -> tuple[int, int]:
    """(max_kb, stale_days) from `[tidy]`; a bad value falls back to the default."""
    from . import config
    t = (cfg or config.load()).get("tidy") or {}

    def num(key, default):
        try:
            v = int(t.get(key, default))
        except (TypeError, ValueError):
            return default
        return v if v > 0 else default
    return num("max_kb", DEFAULT_MAX_KB), num("stale_days", DEFAULT_STALE_DAYS)


# --- a parsed file ------------------------------------------------------------------------------

class Doc:
    """One markdown file: its lines (no line ending), the line endings, and which lines are
    protected (code fences, teyla:protect regions, regions Teyla generates) or frontmatter."""

    def __init__(self, path: pathlib.Path, raw: bytes, sig: tuple[int, int] | None = None):
        self.path = path
        self.raw = raw
        self.sig = sig  # (mtime_ns, size) when the bytes were read, to notice a save made since
        self.text = raw.decode("utf-8")  # the caller turns a decode error into "unreadable"
        pieces = [p for p in re.split(r"(?<=\n)", self.text) if p != ""]
        self.pieces = pieces
        self.eols = ["\r\n" if p.endswith("\r\n") else "\n" if p.endswith("\n") else "" for p in pieces]
        self.lines = [p[:len(p) - len(e)] for p, e in zip(pieces, self.eols)]
        self.protected = _protected_lines(self.lines)
        self.front = _frontmatter_lines(self.lines)

    def blank(self, i: int) -> bool:
        return not self.lines[i].strip()

    def prose(self, i: int) -> bool:
        """A line the scanners may look at: not protected, not frontmatter."""
        return not self.protected[i] and not self.front[i]


def _protected_lines(lines: list[str]) -> list[bool]:
    """One flag per line: inside a code fence (any fence, so the owner's MERGE-APPROVED list is
    covered whatever its indentation or fence character), a teyla:protect region, or a region
    Teyla itself generates. An unclosed region runs to the end of the file."""
    n = len(lines)
    prot = [False] * n
    i = 0
    while i < n:
        line = lines[i]
        if line.strip() == PROTECT_START:
            j = i
            while j < n and lines[j].strip() != PROTECT_END:
                j += 1
            for k in range(i, min(j, n - 1) + 1):  # an unclosed region runs to the end of the file
                prot[k] = True
            i = j + 1
            continue
        managed_end = next((end for start, end in _MANAGED if start.search(line)), None)
        if managed_end is not None:
            j = i + 1
            while j < n and not managed_end.search(lines[j]):
                j += 1
            for k in range(i, min(j, n - 1) + 1):
                prot[k] = True
            i = j + 1
            continue
        depth, rest = _quote_depth(line)
        m = FENCE_RE.match(rest)
        if m and not (m.group(1)[0] == "`" and "`" in m.group(2)):
            fence, ch = m.group(1), m.group(1)[0]
            close = re.compile(r"^\s*" + re.escape(ch) + "{" + str(len(fence)) + r",}\s*$")
            # CommonMark: a fence closes with the same character, at least as long, at the same
            # blockquote depth. A `> ```` line inside a plain fence is code, not a closer.
            j = i + 1
            while j < n:
                d2, rest2 = _quote_depth(lines[j])
                if d2 == depth and close.match(rest2):
                    break
                j += 1
            for k in range(i, min(j, n - 1) + 1):
                prot[k] = True
            i = j + 1
            continue
        i += 1
    return prot


def _frontmatter_lines(lines: list[str]) -> list[bool]:
    front = [False] * len(lines)
    if lines and lines[0].strip() == "---":
        for j in range(1, min(len(lines), 80)):
            if lines[j].strip() == "---":
                for k in range(j + 1):
                    front[k] = True
                break
    return front


def frontmatter_keys(doc: Doc) -> dict[str, str]:
    """`key: value` pairs of a leading --- block (single-line scalars, as memory files use)."""
    out: dict[str, str] = {}
    if not doc.front or not doc.front[0]:
        return out
    for line in doc.lines[1:]:
        if line.strip() == "---":
            break
        k, sep, v = line.partition(":")
        if sep and k.strip():
            out[k.strip()] = v.strip().strip("\"'")
    return out


def is_generated(text: str) -> bool:
    """A file `teyla policy sync` or `teyla harness sync` writes: it carries a generated-by marker
    near the top. Editing the copy is pointless; the source is the file to tidy."""
    for line in text.splitlines()[:12]:
        if line.startswith(_GENERATED):
            return True
    return False


# --- targets ------------------------------------------------------------------------------------

def repo_targets(repo: pathlib.Path) -> list[pathlib.Path]:
    out = [repo / "CLAUDE.md", repo / "AGENTS.md"]
    rules = repo / ".claude" / "rules"
    if rules.is_dir():
        try:
            out += sorted(rules.rglob("*.md"))
        except OSError:
            pass
    return [p for p in out if p.is_file()]


def _is_memory_dir(d: pathlib.Path) -> bool:
    """A memory directory has a MEMORY.md index, or is `projects/<key>/memory`."""
    return (d / "MEMORY.md").exists() or (d.name == "memory" and d.parent.parent.name == "projects")


def default_targets(cfg: dict | None = None) -> list[pathlib.Path]:
    """The global files, every project's memory, and each repo's governance files."""
    from . import config, detect
    cfg = cfg or config.load()
    home = _home()
    out = [p for p in (home / ".agents" / "POLICY.md", home / ".claude" / "CLAUDE.md") if p.is_file()]
    projects = home / ".claude" / "projects"
    if projects.is_dir():
        try:
            out += sorted(p for p in projects.glob("*/memory/*.md") if p.is_file())
        except OSError:
            pass
    try:
        repos = detect.repos(cfg)
    except Exception:  # noqa: BLE001 — an unreadable root must not stop the global files being tidied
        repos = []
    for repo in repos:
        out += repo_targets(repo)
    return _unique(out)


def resolve_targets(paths: list[str]) -> tuple[list[pathlib.Path], list[str]]:
    """(files, errors). A file is taken as given; a directory yields its governance files, its
    memory files when it is a memory directory, else the markdown files directly in it."""
    out: list[pathlib.Path] = []
    errors: list[str] = []
    for raw in paths:
        p = pathlib.Path(raw).expanduser()
        if p.is_file():
            out.append(p)
        elif p.is_dir():
            found = repo_targets(p)
            if _is_memory_dir(p):
                found += sorted(q for q in p.glob("*.md") if q.is_file())
            if not found:
                found = sorted(q for q in p.glob("*.md") if q.is_file())
            out += found
        else:
            errors.append(f"no such file or directory: {raw}")
    return _unique(out), errors


def _unique(paths: list[pathlib.Path]) -> list[pathlib.Path]:
    """One entry per real file: AGENTS.md symlinked to CLAUDE.md is scanned once."""
    seen, out = set(), []
    for p in paths:
        try:
            key = p.resolve()
        except OSError:
            key = p
        if key not in seen:
            seen.add(key)
            out.append(p)
    return out


def _in_repo(path: pathlib.Path) -> bool:
    """Whether the file lives inside a git repository (below, never at, the home directory)."""
    home = _home().resolve()
    try:
        d = path.resolve().parent
    except OSError:
        return False
    while True:
        if d == home:
            return False
        if (d / ".git").exists():
            return True
        if d.parent == d:
            return False
        d = d.parent


# --- findings -----------------------------------------------------------------------------------

def _finding(doc: Doc | pathlib.Path, line: int, rule: str, message: str, fix: str, auto: bool = False) -> dict:
    path = doc.path if isinstance(doc, Doc) else doc
    return dict(file=str(path), line=line, rule=rule, message=message, fix=fix, auto=auto)


def _norm(text: str) -> str:
    """Whitespace collapsed outside backtick spans; inside a span it is part of the code."""
    parts = re.split(r"(`[^`\n]*`)", text)
    return "".join(part if i % 2 else re.sub(r"\s+", " ", part) for i, part in enumerate(parts)).strip()


def _item_key(line: str) -> tuple[str, bool] | None:
    """(comparison key, is a list item) for a line the duplicate checks may use, else None."""
    if HEADING_RE.match(line) or HR_RE.match(line) or line.lstrip().startswith("|"):
        return None
    m = LIST_RE.match(line)
    key = _norm(m.group(3) if m else line)
    if len(key) < (DUP_MIN if m else PARA_MIN) or (not m and _LABEL_RE.match(key)):
        return None  # short lines and bold labels ("**Setup**") repeat legitimately
    return key, bool(m)


def _indent(line: str) -> int:
    t = line.expandtabs(4)
    return len(t) - len(t.lstrip())


def _deletable_bullet(doc: Doc, i: int) -> bool:
    """Whether line i is a bullet that stands alone, so removing it removes exactly one item:
    nothing continues it (a wrapped line, a nested bullet, a fence or paragraph under it)."""
    if not BULLET_RE.match(doc.lines[i]):
        return False
    n = len(doc.lines)
    nxt = doc.lines[i + 1] if i + 1 < n else ""
    if nxt.strip() and not (LIST_RE.match(nxt) or HEADING_RE.match(nxt) or HR_RE.match(nxt)):
        return False  # a wrapped continuation, a fence, a table
    k = i + 1
    while k < n and doc.blank(k):
        k += 1
    return not (k < n and _indent(doc.lines[k]) > _indent(doc.lines[i]))  # a child belongs to this item


def _is_hard_break(doc: Doc, i: int) -> bool:
    line = doc.lines[i]
    return line.endswith("  ") and bool(line.strip()) and i + 1 < len(doc.lines) and not doc.blank(i + 1)


class Plan:
    """The mechanical fixes for one file, computed once: findings and --apply both read it."""

    def __init__(self, doc: Doc):
        n = len(doc.lines)
        self.ws: set[int] = set()        # trailing whitespace stripped
        self.tab: set[int] = set()       # leading tabs of a list line become spaces
        self.drop_blank: set[int] = set()  # blank lines beyond the first of a long run
        self.dup: dict[int, int] = {}    # later copy -> first copy, both single-bullet safe
        self.blank_runs: list[tuple[int, int]] = []
        for i in range(n):
            if not doc.prose(i):
                continue
            line = doc.lines[i]
            if line != line.rstrip(" \t") and not _is_hard_break(doc, i):
                self.ws.add(i)
            m = LIST_RE.match(line.replace("\t", "    ")) if "\t" in line else None
            if m and "\t" in re.match(r"^\s*", line).group(0):
                self.tab.add(i)
        i = 0
        while i < n:
            if doc.prose(i) and doc.blank(i):
                j = i
                while j + 1 < n and doc.prose(j + 1) and doc.blank(j + 1):
                    j += 1
                if j - i + 1 > 2:
                    self.blank_runs.append((i, j))
                    self.drop_blank.update(range(i + 1, j + 1))
                i = j + 1
            else:
                i += 1
        first: dict[str, int] = {}
        for i in range(n):
            if not doc.prose(i):
                continue
            ik = _item_key(doc.lines[i])
            if ik is None:
                continue
            key, _ = ik
            if key in first:
                f = first[key]
                # Whole items must match: both single standalone bullets, the same text to the
                # character (only trailing whitespace trimmed), so a first copy with a wrapped
                # exception line, or a code span with different spacing, never costs the later one.
                if (doc.lines[i].rstrip() == doc.lines[f].rstrip()
                        and _deletable_bullet(doc, i) and _deletable_bullet(doc, f)):
                    self.dup[i] = f
            else:
                first[key] = i
        # A bullet removed between two blank lines leaves two; take the second as well.
        for i in sorted(self.dup):
            if i > 0 and doc.blank(i - 1) and doc.prose(i - 1) and i + 1 < n and doc.blank(i + 1) and doc.prose(i + 1):
                self.drop_blank.add(i + 1)

    def empty(self) -> bool:
        return not (self.ws or self.tab or self.drop_blank or self.dup)

    def counts(self) -> dict[str, int]:
        c = {"trailing-ws": len(self.ws), "tab-list": len(self.tab), "blank-run": len(self.drop_blank),
             "dup-line": len(self.dup)}
        return {k: v for k, v in c.items() if v}

    def render(self, doc: Doc) -> str:
        out = []
        for i, line in enumerate(doc.lines):
            if i in self.dup or i in self.drop_blank:
                continue
            if i in self.tab:
                lead = re.match(r"^\s*", line).group(0)
                line = lead.replace("\t", "    ") + line[len(lead):]
            if i in self.ws:
                line = line.rstrip(" \t")
            out.append(line + doc.eols[i])
        return "".join(out)


def _local_target(target: str) -> str | None:
    t = target.strip()
    if t.startswith("<") and t.endswith(">"):
        t = t[1:-1]
    if not t or t.startswith("#") or _URL_RE.match(t) or any(c in t for c in "<>{}$*|"):
        return None
    t = re.split(r"[#?]", t, maxsplit=1)[0]
    if not t:
        return None
    from urllib.parse import unquote
    return unquote(t)


def _resolve(ref: str, base: pathlib.Path) -> pathlib.Path | None:
    """The file a link or import names, or None when it cannot be judged (a site-root link)."""
    home = _home()
    if ref.startswith("~/"):
        return home / ref[2:]
    if ref.startswith("/"):
        return pathlib.Path(ref) if ref.startswith(str(home) + "/") else None
    return base / ref


def _exists(p: pathlib.Path) -> bool:
    try:
        return p.exists() or os.path.lexists(p)
    except OSError:
        return False


def _imports(line: str) -> list[str]:
    """`@path` imports on a line, outside inline code."""
    out = []
    for m in re.finditer(r"(?<![\w@./:~\-])@(\S+)", CODE_SPAN_RE.sub("", line)):
        tok = m.group(1).rstrip(".,;:!?)]}>'\"")
        if _PREFIXED_PATH.fullmatch(tok) or _BARE_PATH.fullmatch(tok):
            if re.search(r"[A-Za-z0-9]", tok.rsplit("/", 1)[-1]):
                out.append(tok)
    return out


class _Memory:
    """The memory directory a file belongs to: names it holds, for `[[name]]` links."""

    def __init__(self, d: pathlib.Path):
        self.dir = d
        self.names: set[str] = set()
        self.files: list[pathlib.Path] = []
        try:
            self.files = sorted(p for p in d.glob("*.md") if p.is_file())
        except OSError:
            pass
        for p in self.files:
            self.names.add(p.stem)
            try:
                for line in p.read_text(encoding="utf-8", errors="replace").splitlines()[:30]:
                    if line.startswith("name:"):
                        self.names.add(line.split(":", 1)[1].strip().strip("\"'"))
                        break
            except OSError:
                pass


def _scan_refs(doc: Doc, mem: _Memory | None, out: list[dict]) -> None:
    is_index = doc.path.name == "MEMORY.md" and mem is not None
    base = doc.path.parent
    for i, line in enumerate(doc.lines):
        if not doc.prose(i):
            continue
        stripped = CODE_SPAN_RE.sub("", line)
        for ref in _imports(line):
            target = _resolve(ref, base)
            if target is not None and not _exists(target):
                out.append(_finding(doc, i + 1, "broken-import", f"@{ref} imports a file that does not exist",
                                    "fix the path or delete the import line"))
        for m in LINK_RE.finditer(stripped):
            ref = _local_target(m.group(1))
            target = _resolve(ref, base) if ref else None
            if target is not None and not _exists(target):
                if is_index:
                    out.append(_finding(doc, i + 1, "memory-index", f"index line points at missing file {ref}",
                                        "delete the line, or restore the file"))
                else:
                    out.append(_finding(doc, i + 1, "broken-link", f"link to {ref}, which does not exist",
                                        "fix the path or remove the link"))
        if mem is not None:
            for m in MEMLINK_RE.finditer(stripped):
                name = m.group(1).strip()
                if name.endswith(".md"):
                    name = name[:-3]
                if name not in mem.names:
                    out.append(_finding(doc, i + 1, "broken-memory-link", f"[[{name}]] names no memory in {mem.dir.name}/",
                                        "link an existing memory or drop the brackets"))


def _scan_memory(doc: Doc, mem: _Memory, out: list[dict]) -> None:
    if doc.path.name == "MEMORY.md":
        listed: set[str] = set()
        last = 1
        for i, line in enumerate(doc.lines):
            if line.strip():
                last = i + 1
            if not doc.prose(i):
                continue
            for m in LINK_RE.finditer(CODE_SPAN_RE.sub("", line)):
                ref = _local_target(m.group(1))
                if ref:
                    listed.add(pathlib.PurePosixPath(ref).name)
            for m in MEMLINK_RE.finditer(line):
                listed.add(m.group(1).strip().removesuffix(".md") + ".md")
            if len(line) > INDEX_LINE_MAX and line.lstrip().startswith(("-", "*")):
                out.append(_finding(doc, i + 1, "size", f"index line is {len(line)} chars (limit {INDEX_LINE_MAX})",
                                    "keep the title and a one-line hook; the detail belongs in the memory file"))
        for p in mem.files:
            if p.name != "MEMORY.md" and p.name not in listed:
                out.append(_finding(doc, last, "memory-unlisted", f"{p.name} is not listed in MEMORY.md",
                                    f"add `- [Title]({p.name}) — one-line hook`, or delete the memory"))
        return
    keys = frontmatter_keys(doc)
    missing = [k for k in ("name", "description", "type") if not keys.get(k)]
    if not doc.front or not doc.front[0]:
        out.append(_finding(doc, 1, "memory-frontmatter", "no frontmatter (needs name, description, type)",
                            "add a --- block with name, description and type"))
    elif missing:
        out.append(_finding(doc, 1, "memory-frontmatter", f"frontmatter lacks {', '.join(missing)}",
                            "add the missing keys"))


def _scan_lines(doc: Doc, plan: Plan, out: list[dict], repo_file: bool, today: _dt.date, stale_days: int) -> None:
    for i in sorted(plan.ws):
        out.append(_finding(doc, i + 1, "trailing-ws", "trailing whitespace", "strip it", auto=True))
    for i in sorted(plan.tab):
        out.append(_finding(doc, i + 1, "tab-list", "tab in a list's indentation", "indent with spaces", auto=True))
    for a, b in plan.blank_runs:
        out.append(_finding(doc, a + 1, "blank-run", f"{b - a + 1} blank lines in a row", "keep one", auto=True))
    cutoff = today - _dt.timedelta(days=stale_days)
    run_start = None
    for i, line in enumerate(doc.lines):
        if not doc.prose(i):
            continue
        if repo_file and CYRILLIC.search(line):
            if run_start is None:
                run_start = i
        elif run_start is not None:
            out.append(_cyrillic_finding(doc, run_start, i - 1))
            run_start = None
        stripped = CODE_SPAN_RE.sub("", line)
        dates = []
        for m in DATE_RE.finditer(stripped):
            try:
                dates.append(_dt.date(int(m.group(1)), int(m.group(2)), int(m.group(3))))
            except ValueError:
                pass
        if dates and max(dates) < cutoff and STALE_WORDS.search(stripped):
            word = STALE_WORDS.search(stripped).group(0)
            out.append(_finding(doc, i + 1, "stale-date",
                                f"dated {max(dates).isoformat()} ({(today - max(dates)).days} days ago) and still says \"{word}\"",
                                "finish it, delete it, or turn it into a rule"))
    if run_start is not None:
        out.append(_cyrillic_finding(doc, run_start, len(doc.lines) - 1))


def _cyrillic_finding(doc: Doc, a: int, b: int) -> dict:
    where = f"lines {a + 1}-{b + 1}" if b > a else "this line"
    return _finding(doc, a + 1, "non-english", f"non-English prose ({where}); everything in a repository is English",
                    "translate it (language data a feature needs goes in a clearly named file)")


def _scan_dups(doc: Doc, plan: Plan, out: list[dict]) -> list[tuple[int, str, bool]]:
    """Exact and near duplicates inside one file. Returns the file's (line, key, is_bullet) items
    for the cross-file pass."""
    items: list[tuple[int, str, bool]] = []
    first: dict[str, int] = {}
    near_pool: list[tuple[int, str]] = []
    for i in range(len(doc.lines)):
        if not doc.prose(i):
            continue
        ik = _item_key(doc.lines[i])
        if ik is None:
            continue
        key, bullet = ik
        items.append((i, key, bullet))
        if key in first:
            auto = i in plan.dup
            out.append(_finding(doc, i + 1, "dup-line", f"same as line {first[key] + 1}: \"{_clip(key)}\"",
                                "delete this copy" + ("" if auto else " by hand (the two items are not identical single-line bullets)"),
                                auto=auto))
            continue
        first[key] = i
        if bullet and len(key) >= NEAR_MIN:
            best = _best_near(key, near_pool)
            if best is not None:
                j, ratio = best
                out.append(_finding(doc, i + 1, "near-dup", f"{ratio:.2f} similar to line {j + 1}: \"{_clip(key)}\"",
                                    "merge the two bullets into one"))
            near_pool.append((i, key))
    return items


def _best_near(key: str, pool: list[tuple[int, str]]) -> tuple[int, float] | None:
    best = None
    for j, other in pool:
        sm = difflib.SequenceMatcher(None, key, other, autojunk=False)
        if sm.real_quick_ratio() < NEAR_RATIO or sm.quick_ratio() < NEAR_RATIO:
            continue
        r = sm.ratio()
        if r >= NEAR_RATIO and (best is None or r > best[1]):
            best = (j, r)
    return best


def _clip(s: str, n: int = 70) -> str:
    return s if len(s) <= n else s[:n - 1] + "…"


def _scan_cross(policy: tuple[Doc, list], claude: tuple[Doc, list], out: list[dict]) -> None:
    """Lines of the owner's CLAUDE.md that POLICY.md already says."""
    pdoc, pitems = policy
    cdoc, citems = claude
    exact = {key: i for i, key, _ in pitems}
    bullets = [(i, key) for i, key, b in pitems if b and len(key) >= NEAR_MIN]
    for i, key, bullet in citems:
        if key in exact:
            out.append(_finding(cdoc, i + 1, "dup-line", f"same as {pdoc.path.name}:{exact[key] + 1}: \"{_clip(key)}\"",
                                f"keep it in one of the two files (report only: the files are separate sources)"))
        elif bullet and len(key) >= NEAR_MIN:
            best = _best_near(key, bullets)
            if best is not None:
                out.append(_finding(cdoc, i + 1, "near-dup",
                                    f"{best[1]:.2f} similar to {pdoc.path.name}:{best[0] + 1}: \"{_clip(key)}\"",
                                    "keep it in one of the two files"))


# --- scan ---------------------------------------------------------------------------------------

def load(paths: list[pathlib.Path]) -> tuple[list[Doc], list[str]]:
    docs, notes = [], []
    for p in paths:
        try:
            raw, sig = _snapshot(p)
            docs.append(Doc(p, raw, sig))
        except (OSError, UnicodeDecodeError) as e:
            notes.append(f"{p}: not read ({type(e).__name__})")
    return docs, notes


def scan(docs: list[Doc], cfg: dict | None = None, today: _dt.date | None = None) -> list[dict]:
    max_kb, stale_days = settings(cfg)
    today = today or _dt.date.today()
    home = _home()
    out: list[dict] = []
    mems: dict[pathlib.Path, _Memory] = {}
    items_by: dict[pathlib.Path, tuple[Doc, list]] = {}
    for doc in docs:
        plan = Plan(doc)
        mem = None
        if _is_memory_dir(doc.path.parent):
            d = doc.path.parent
            mem = mems.get(d) or mems.setdefault(d, _Memory(d))
        if len(doc.raw) > max_kb * 1024:
            out.append(_finding(doc, 1, "size", f"{len(doc.raw) / 1024:.1f} KB, over the {max_kb} KB budget",
                                "move one-off history out of this always-loaded file"))
        _scan_lines(doc, plan, out, _in_repo(doc.path), today, stale_days)
        items = _scan_dups(doc, plan, out)
        try:
            items_by[doc.path.resolve()] = (doc, items)
        except OSError:
            pass
        _scan_refs(doc, mem, out)
        if mem is not None:
            _scan_memory(doc, mem, out)
    try:
        pol, cla = (home / ".agents" / "POLICY.md").resolve(), (home / ".claude" / "CLAUDE.md").resolve()
    except OSError:
        pol = cla = None
    if pol in items_by and cla in items_by and pol != cla:
        _scan_cross(items_by[pol], items_by[cla], out)
    out.sort(key=lambda f: (f["file"], f["line"], f["rule"]))
    return out


def summarize(findings: list[dict]) -> tuple[int, int]:
    return len(findings), len({f["file"] for f in findings})


# --- apply --------------------------------------------------------------------------------------

def _protected_pieces(doc: Doc) -> list[str]:
    return [p for p, prot in zip(doc.pieces, doc.protected) if prot]


def _flatten(path: pathlib.Path) -> str:
    return str(path.absolute()).lstrip("/").replace("/", "__")


def apply(docs: list[Doc], now: _dt.datetime | None = None) -> tuple[list[dict], list[dict]]:
    """Write the mechanical fixes. Returns (applied, refused); each has the file, and a refused
    one the reason. A backup of every file is written before it is touched."""
    from . import config
    now = now or _dt.datetime.now()
    stamp_dir = _teyla_dir() / "tidy-backup" / now.strftime("%Y-%m-%d-%H%M%S")
    applied: list[dict] = []
    refused: list[dict] = []
    for doc in docs:
        plan = Plan(doc)
        if plan.empty():
            continue
        path = doc.path
        why = None
        if path.is_symlink():
            why = "is a symlink (nothing is written through a link; tidy its target)"
        elif is_generated(doc.text):
            why = "is generated by `teyla policy sync` / `harness sync`; tidy the source it names"
        elif not os.access(path, os.W_OK):
            why = "is not writable"
        if why:
            refused.append(dict(file=str(path), reason=why))
            continue
        new_text = plan.render(doc)
        try:
            check = Doc(path, new_text.encode("utf-8"))
        except UnicodeDecodeError:
            check = None
        if check is None or _protected_pieces(check) != _protected_pieces(doc):
            refused.append(dict(file=str(path), reason="the fix would have changed a protected block; nothing written"))
            continue
        if _symlinked_ancestor(path):
            refused.append(dict(file=str(path), reason="sits below a symlinked directory (tidy the real path)"))
            continue
        tmp = None
        backup = None
        try:
            mode = path.stat().st_mode & 0o7777
            tmp = _write_temp(path, new_text.encode("utf-8"), mode)
            # Compare-and-replace: what is on disk right now must be what the fix was computed
            # from (bytes, mtime and size). The backup holds exactly those bytes, and the check
            # is repeated as the last step before the rename: nothing runs between the final
            # compare and os.replace. A save landing inside that one syscall gap is the only
            # window left (a rename cannot be made conditional on content).
            cur, sig = _snapshot(path, nofollow=True)
            if cur != doc.raw or (doc.sig is not None and sig != doc.sig):
                refused.append(dict(file=str(path), reason="changed while tidy ran; nothing written"))
                continue
            config.private_dir(stamp_dir.parent)
            config.private_dir(stamp_dir)
            backup = stamp_dir / _flatten(path)
            n = 1
            while backup.exists():
                backup = stamp_dir / f"{_flatten(path)}.{n}"
                n += 1
            fd = os.open(backup, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            try:
                config.write_all(fd, cur)
            finally:
                os.close(fd)
            if _snapshot(path, nofollow=True) != (cur, sig):
                os.unlink(backup)
                refused.append(dict(file=str(path), reason="changed while tidy ran; nothing written"))
                continue
            os.replace(tmp, path)
            tmp = None
        except OSError as e:
            refused.append(dict(file=str(path), reason=f"not written ({e.strerror or type(e).__name__})"))
            continue
        finally:
            if tmp is not None:
                try:
                    os.unlink(tmp)
                except OSError:
                    pass
        applied.append(dict(file=str(path), backup=str(backup), fixed=plan.counts()))
    return applied, refused


def _snapshot(path: pathlib.Path, nofollow: bool = False) -> tuple[bytes, tuple[int, int]]:
    """(bytes, (mtime_ns, size)) read through one descriptor. A write path passes nofollow, so a link
    swapped in after the symlink check is not followed; a scan reads through links."""
    fd = os.open(path, os.O_RDONLY | (getattr(os, "O_NOFOLLOW", 0) if nofollow else 0))
    try:
        st = os.fstat(fd)
        chunks = []
        while True:
            chunk = os.read(fd, 1 << 20)
            if not chunk:
                break
            chunks.append(chunk)
    finally:
        os.close(fd)
    return b"".join(chunks), (st.st_mtime_ns, st.st_size)


def _write_temp(path: pathlib.Path, data: bytes, mode: int) -> str:
    """The new content in a fresh, unpredictably named file beside `path` (O_CREAT|O_EXCL, so an
    existing name or a planted link is never opened), with the original's permission bits."""
    from . import config
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tidy-tmp", dir=path.parent)
    try:
        try:
            config.write_all(fd, data)
        finally:
            os.close(fd)
        os.chmod(tmp, mode)
    except OSError:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    return tmp


def _symlinked_ancestor(path: pathlib.Path) -> bool:
    """Whether a directory between the file and its anchor (the repository root, else the home
    directory, else the file's own directory) is a symlink: writing there rewrites a file that
    lives somewhere else, shared by whoever else links to it. Links above the anchor (a /tmp or
    /var that is itself a link) are the machine's layout, not the file's. A repository root that is
    itself a link (or whose .git is one) is another checkout reached through the link: refused too."""
    d = pathlib.Path(os.path.abspath(path)).parent
    anchors = {os.path.abspath(_home()), os.path.realpath(_home())}
    chain = []
    while True:
        if str(d) in anchors or (d / ".git").exists():
            if str(d) not in anchors and (d.is_symlink() or (d / ".git").is_symlink()):
                return True  # the "repository" is another checkout reached through a link
            return any(c.is_symlink() for c in chain)
        chain.append(d)
        if d.parent == d:  # no repository and not under home: only the file's own directory counts
            return chain[0].is_symlink()
        d = d.parent


# --- report -------------------------------------------------------------------------------------

def _tilde(p: str) -> str:
    h = str(_home())
    return "~" + p[len(h):] if p == h or p.startswith(h + "/") else p


def render_text(findings: list[dict], scanned: int, applied: list[dict], refused: list[dict], notes: list[str]) -> str:
    n, m = summarize(findings)
    lines = []
    if n:
        lines.append(f"# teyla tidy: {n} finding(s) in {m} file(s)")
    else:
        lines.append(f"teyla tidy: clean ({scanned} file(s) scanned)")
    for a in applied:
        fixed = ", ".join(f"{k} x{v}" for k, v in a["fixed"].items())
        lines.append(f"applied to {_tilde(a['file'])}: {fixed}; backup {_tilde(a['backup'])}")
    for r in refused:
        lines.append(f"refused {_tilde(r['file'])}: {r['reason']}")
    lines += notes
    cur = None
    for f in findings:
        if f["file"] != cur:
            cur = f["file"]
            lines += ["", f"## {_tilde(cur)}"]
        tag = " (auto-fixable)" if f["auto"] else ""
        lines.append(f"- line {f['line']} [{f['rule']}] {f['message']} → {f['fix']}{tag}")
    auto = sum(1 for f in findings if f["auto"])
    if auto:
        lines += ["", f"{auto} finding(s) are mechanical: `teyla tidy --apply` fixes them after a backup. "
                      "The rest is yours, or the `tidy` skill's, to propose."]
    return "\n".join(lines) + "\n"


def run(paths: list[str], apply_fixes: bool = False, cfg: dict | None = None, today: _dt.date | None = None) -> dict:
    from . import config
    cfg = cfg or config.load()
    if paths:
        files, errors = resolve_targets(paths)
    else:
        files, errors = default_targets(cfg), []
    docs, notes = load(files)
    applied: list[dict] = []
    refused: list[dict] = []
    if apply_fixes and not errors:
        applied, refused = apply(docs)
        if applied:
            docs, notes2 = load(files)
            notes += [x for x in notes2 if x not in notes]
    findings = scan(docs, cfg, today)
    n, m = summarize(findings)
    return dict(scanned=[str(d.path) for d in docs], findings=findings, applied=applied, refused=refused,
                notes=notes, errors=errors, summary=dict(findings=n, files=m, auto_fixable=sum(1 for f in findings if f["auto"])))


def digest_candidates() -> list[dict]:
    """One digest line when the default targets hold any finding. Reads only; never applies."""
    r = run([])
    n, m = r["summary"]["findings"], r["summary"]["files"]
    if not n:
        return []
    return [dict(rank=5, id="tidy:findings", text=f"md tidy: {n} finding(s) in {m} file(s)", step="teyla tidy", cmd=True)]


def cmd_tidy(args) -> int:
    r = run(args.paths, apply_fixes=args.apply)
    if r["errors"]:
        for e in r["errors"]:
            print(f"teyla tidy: {e}", file=sys.stderr)
        return 2
    if args.json:
        print(json.dumps({k: r[k] for k in ("scanned", "summary", "findings", "applied", "refused", "notes")}, indent=2))
    elif r["summary"]["findings"] or r["applied"] or r["refused"] or not args.quiet:
        sys.stdout.write(render_text(r["findings"], len(r["scanned"]), r["applied"], r["refused"], r["notes"]))
    return 1 if r["refused"] else 0


def register(sp):
    q = sp.add_parser("tidy", help="find duplicates, dead references and whitespace junk in CLAUDE.md, AGENTS.md, "
                                   "rules, POLICY.md and memory; --apply fixes only the mechanical part")
    q.set_defaults(fn=cmd_tidy)
    q.add_argument("paths", nargs="*", help="files or directories (default: the global rule files, all memory, and every repo's governance files)")
    q.add_argument("--json", action="store_true")
    q.add_argument("--apply", action="store_true",
                   help="fix trailing whitespace, blank-line runs, tabs in lists and an exact duplicate bullet; backup first; nothing else")
    q.add_argument("--quiet", action="store_true", help="print nothing when there is nothing to report (the weekly routine)")
    return q
