"""`teyla uninstall [--dry] [--keep-data]` — undo every write Teyla makes on this machine.

Derived from the writers, not from memory; each line below names the module that writes it:

    ~/Library/LaunchAgents/com.zaitsew.teyla.{daily,weekly}.plist   routine_install  unload + remove
    ~/Library/LaunchAgents/com.teyla.<product>.<routine>.plist      control.triggers unload + remove
    ~/Library/Logs/teyla-{daily,weekly}.log, com.teyla.*.log        routine_install, triggers  remove
    ~/.claude/CLAUDE.md          the `@~/.agents/POLICY.md` import   policy.sync      edit: drop that line
    ~/.codex/AGENTS.md, ~/.grok/AGENTS.md   symlinks → POLICY.md      policy.sync      remove, only if they point there
    ~/.hermes/SOUL.md            the "## Operating policy" section   policy.sync      edit: drop it, only verbatim
    ~/.hermes/config.yaml        the `# teyla-hooks begin/end` block harness.sync     edit: drop the block
    ~/.cursor/skills/teyla-policy/SKILL.md                            policy.sync      remove (generated-by marker)
    ~/.{cursor,codex,grok}/skills/*/SKILL.md, ~/.hermes/skills/teyla/  harness.sync     remove (generated-by marker)
    ~/.cursor/hooks.json         entries running ~/.teyla/hooks/*    harness.sync     edit: drop those entries
    ~/.grok/hooks/teyla.json                                          harness.sync     remove
    the Claude Code plugin teyla@<marketplace>                        plugin_install / `claude plugin install`
                                 `claude plugin uninstall` + `marketplace remove` when `claude` exists,
                                 else the registry rows and cache copy Teyla wrote itself
    ~/.teyla/                    config, caches, doctor state, hooks, wrappers, control plane   remove
                                 (--keep-data keeps it, minus hooks/ and the wrappers: code, not data)

Reported, never deleted — they are the owner's now, or they live in the owner's repos:

    ~/.agents/POLICY.md (+ .bak-* copies)   written once from a template, then edited by its owner
    <repo>/.teyla/corrections.jsonl          the capture hook and `teyla correct`
    <repo>/.claude/rules/*.md                `teyla rule` — rules the owner asked for
    the weekly routine's run output under the ops root, registry backups (*.bak-<date>)

Every step checks that its target is recognisably Teyla's (a fixed label, a generated-by
marker, a symlink into POLICY.md, a block between Teyla's markers) and leaves anything else
alone with a line saying why. Running it twice is safe: the second run finds nothing to do.
`--dry` prints every action and touches nothing — it is also the answer to "which files has
Teyla written on this machine?".
"""
from __future__ import annotations

import datetime as _dt
import json
import os
import pathlib
import shutil
import subprocess
import sys

from . import harness as _harness, policy as _policy, routine_install as _ri

SKILL_MARKERS = ("generated by `teyla harness sync`", "generated by `teyla policy sync`")
ROUTINE_LABELS = (_ri.DAILY_LABEL, _ri.LABEL)
TRIGGER_PREFIX = "com.teyla."


class Step:
    """One thing uninstall does (`fn` set) or only reports (`fn` None)."""

    def __init__(self, verb: str, target, why: str, fn=None):
        self.verb, self.target, self.why, self.fn = verb, str(target), why, fn

    def line(self, dry: bool) -> str:
        if self.fn is None:
            return f"keep    {self.target} — {self.why}"
        return f"{'would ' if dry else ''}{self.verb} {self.target} — {self.why}"


# --- small, patchable seams: tests replace these, nothing else shells out ------------------

def _launchctl_list() -> str:
    if sys.platform != "darwin" or not shutil.which("launchctl"):
        return ""
    try:
        return subprocess.run(["launchctl", "list"], capture_output=True, text=True, timeout=10).stdout
    except (OSError, subprocess.SubprocessError):
        return ""


def _run(cmd: list[str]) -> tuple[int, str]:
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    except (OSError, subprocess.SubprocessError) as e:
        return 1, str(e)
    return r.returncode, (r.stdout + r.stderr).strip()


def _claude_bin() -> str | None:
    return shutil.which("claude")


# --- helpers ----------------------------------------------------------------------------------

def _loaded_labels() -> set[str]:
    out = set()
    for line in _launchctl_list().splitlines():
        parts = line.split("\t")
        if len(parts) >= 3:
            out.add(parts[2].strip())
    return out


def _unload(label: str, plist: pathlib.Path) -> None:
    uid = os.getuid()
    rc, _ = _run(["launchctl", "bootout", f"gui/{uid}/{label}"])
    if rc != 0 and plist.exists():
        _run(["launchctl", "unload", str(plist)])


def _rm(p: pathlib.Path) -> None:
    if p.is_symlink() or p.is_file():
        p.unlink()
    elif p.is_dir():
        shutil.rmtree(p)


def _rmdir_empty(p: pathlib.Path, stop: pathlib.Path) -> None:
    """Remove `p` and its parents while they are empty, never `stop` or above it."""
    try:
        while p != stop and stop in p.parents and p.is_dir() and not any(p.iterdir()):
            p.rmdir()
            p = p.parent
    except OSError:
        pass


def _backup(p: pathlib.Path) -> pathlib.Path:
    bak = p.with_name(f"{p.name}.bak-{_dt.date.today().isoformat()}")
    if not bak.exists():
        shutil.copy2(p, bak)
    return bak


def _expand(path: str, home: pathlib.Path) -> pathlib.Path:
    return home / path[2:] if path.startswith("~/") else pathlib.Path(path)


# --- the plan ---------------------------------------------------------------------------------

def _is_trigger_plist(p: pathlib.Path) -> bool:
    """A `teyla triggers install` plist: its program is a `teyla` binary and its first argument
    `run` (control.triggers.plist_for). The label alone proves nothing — anyone can name a job
    com.teyla.*, and the label string would satisfy a text search for "teyla"."""
    import plistlib
    try:
        args = plistlib.loads(p.read_bytes()).get("ProgramArguments") or []
    except Exception:  # noqa: BLE001 — unreadable or not a plist: not recognisably ours
        return False
    prog = args[0] if args and isinstance(args[0], str) else ""
    # triggers.teyla_bin(): the `teyla` on PATH, else sys.argv[0] — which under a checkout's
    # `python -m teyla` is <checkout>/src/teyla/__main__.py
    is_teyla = os.path.basename(prog) == "teyla" or prog.replace("\\", "/").endswith("/teyla/__main__.py")
    return len(args) >= 3 and is_teyla and args[1] == "run"


def _launch_agents(home: pathlib.Path) -> list[Step]:
    steps = []
    agents = home / "Library" / "LaunchAgents"
    loaded = _loaded_labels()
    labels = [(lbl, agents / f"{lbl}.plist") for lbl in ROUTINE_LABELS]
    if agents.is_dir():
        for p in sorted(agents.glob(f"{TRIGGER_PREFIX}*.plist")):
            if _is_trigger_plist(p):
                labels.append((p.stem, p))
            else:
                steps.append(Step("", p, "named like a Teyla trigger but does not run `teyla run`; not Teyla's"))
    for label, plist in labels:
        if label in loaded:
            steps.append(Step("unload", label, "launchd agent Teyla loaded",
                              lambda label=label, plist=plist: _unload(label, plist)))
        if plist.exists():
            steps.append(Step("remove", plist, "its plist", lambda plist=plist: _rm(plist)))
    logs = home / "Library" / "Logs"
    for name in ("teyla-daily.log", "teyla-weekly.log"):
        if (logs / name).exists():
            steps.append(Step("remove", logs / name, "routine log", lambda p=logs / name: _rm(p)))
    if logs.is_dir():
        for p in sorted(logs.glob(f"{TRIGGER_PREFIX}*.log")):
            steps.append(Step("remove", p, "trigger log", lambda p=p: _rm(p)))
    return steps


def _claude_md(home: pathlib.Path) -> list[Step]:
    p = home / ".claude" / "CLAUDE.md"
    if not p.is_file():
        return []
    text = p.read_text()
    if not any(line.strip() == _policy.IMPORT_LINE for line in text.splitlines()):
        return []

    def edit():
        cur = p.read_text()
        appended = f"\n\n## How to run a session\n\n{_policy.IMPORT_LINE}\n"
        if cur.endswith(appended):  # exactly what `policy sync` appended: take the heading too
            new = cur[: -len(appended)].rstrip("\n") + "\n"
        else:
            new = "".join(l for l in cur.splitlines(keepends=True) if l.strip() != _policy.IMPORT_LINE)
        _backup(p)
        p.write_text(new)
    return [Step("edit", p, f"drop the `{_policy.IMPORT_LINE}` import line (backup: CLAUDE.md.bak-<date>)", edit)]


def _policy_links(home: pathlib.Path) -> list[Step]:
    steps = []
    policy_file = home / ".agents" / "POLICY.md"
    for h in ("codex", "grok"):
        p = home / f".{h}" / "AGENTS.md"
        if not (p.exists() or p.is_symlink()):
            continue
        if p.is_symlink() and os.path.realpath(p) == os.path.realpath(policy_file):
            steps.append(Step("remove", p, "symlink → ~/.agents/POLICY.md", lambda p=p: p.unlink()))
        else:
            steps.append(Step("", p, "not a symlink to ~/.agents/POLICY.md; not Teyla's"))
    return steps


def _hermes(home: pathlib.Path) -> list[Step]:
    steps = []
    soul = home / ".hermes" / "SOUL.md"
    if soul.is_file():
        text = soul.read_text()
        if _policy.HERMES_BLOCK in text:
            def edit_soul():
                t = soul.read_text().replace(_policy.HERMES_BLOCK, "")
                soul.write_text(t.rstrip("\n") + "\n")
            steps.append(Step("edit", soul, f"drop the \"{_policy.HERMES_MARK}\" section", edit_soul))
        elif _policy.HERMES_MARK in text:
            steps.append(Step("", soul, f"has a \"{_policy.HERMES_MARK}\" section that is not the text Teyla writes (edited, or written by hand) — remove it by hand"))
    cfg = home / ".hermes" / "config.yaml"
    if cfg.is_file():
        text = cfg.read_text()
        a, b = text.find(_harness.HERMES_BEGIN), text.find(_harness.HERMES_END)
        if a >= 0 and b > a:
            def edit_cfg():
                t = cfg.read_text()
                s, e = t.find(_harness.HERMES_BEGIN), t.find(_harness.HERMES_END) + len(_harness.HERMES_END)
                head, tail = t[:s].rstrip("\n"), t[e:].lstrip("\n")
                cfg.write_text((head + "\n" if head else "") + (("\n" if head else "") + tail if tail else ""))
            steps.append(Step("edit", cfg, "drop the `# teyla-hooks begin … end` block", edit_cfg))
    return steps


def _skills(home: pathlib.Path) -> list[Step]:
    steps = []
    roots = [home / ".cursor" / "skills", home / ".codex" / "skills", home / ".grok" / "skills",
             home / ".hermes" / "skills" / "teyla"]
    for root in roots:
        if not root.is_dir():
            continue
        for skill in sorted(root.glob("*/SKILL.md")):
            try:
                text = skill.read_text(errors="replace")
            except OSError:
                continue
            if any(m in text for m in SKILL_MARKERS):
                # up to the harness's own directory: an emptied skills/ (and Hermes's skills/teyla/)
                # goes too, ~/.codex itself never
                stop = home / root.relative_to(home).parts[0]
                steps.append(Step("remove", skill.parent, "skill Teyla generated (generated-by marker)",
                                  lambda skill=skill, stop=stop: (_rm(skill.parent), _rmdir_empty(skill.parent.parent, stop))))
            elif skill.parent.name.startswith("teyla"):
                steps.append(Step("", skill, "named like Teyla's but has no generated-by marker; not touched"))
    return steps


def _hooks(home: pathlib.Path) -> list[Step]:
    steps = []
    hooks_dir = str(home / ".teyla" / "hooks")
    cur = home / ".cursor" / "hooks.json"
    if cur.is_file():
        try:
            data = json.loads(cur.read_text())
        except ValueError:
            data = None
        ours = lambda e: isinstance(e, dict) and str(e.get("command", "")).startswith(hooks_dir)
        if isinstance(data, dict) and any(ours(e) for v in (data.get("hooks") or {}).values() for e in (v or [])):
            def edit_cursor():
                d = json.loads(cur.read_text())
                hooks = {k: [e for e in (v or []) if not ours(e)] for k, v in (d.get("hooks") or {}).items()}
                d["hooks"] = {k: v for k, v in hooks.items() if v}
                if d == {"version": 1, "hooks": {}}:  # nothing left but the shell Teyla created
                    cur.unlink()
                else:
                    cur.write_text(json.dumps(d, indent=2) + "\n")
            steps.append(Step("edit", cur, "drop the entries that run ~/.teyla/hooks/* (the file goes if nothing else is left)", edit_cursor))
    grok = home / ".grok" / "hooks" / "teyla.json"
    if grok.is_file():
        try:
            data = json.loads(grok.read_text())
            cmds = [h.get("command", "") for v in (data.get("hooks") or {}).values() for g in v for h in g.get("hooks", [])]
        except (ValueError, AttributeError, TypeError):
            cmds = []
        if cmds and all(str(c).startswith(hooks_dir) for c in cmds):
            steps.append(Step("remove", grok, "Grok hooks Teyla wrote",
                              lambda: (_rm(grok), _rmdir_empty(grok.parent, home / ".grok"))))
        else:
            steps.append(Step("", grok, "does not only run ~/.teyla/hooks/*; not touched"))
    return steps


def _is_teyla_marketplace(name: str, entry: dict) -> bool:
    src = (entry or {}).get("source") or {}
    if src.get("source") == "github":
        return str(src.get("repo", "")).rstrip("/").endswith("/teyla")
    loc = pathlib.Path(str(src.get("path") or entry.get("installLocation") or ""))
    try:
        return json.loads((loc / ".claude-plugin" / "marketplace.json").read_text()).get("name") == name == "teyla"
    except (OSError, ValueError, AttributeError):
        return False


def _plugin(home: pathlib.Path) -> list[Step]:
    from . import plugin_install
    plugins = home / ".claude" / "plugins"
    try:
        installed = plugin_install._load_json(plugins / "installed_plugins.json")
        known = plugin_install._load_json(plugins / "known_marketplaces.json")
    except plugin_install.InstallError as e:
        return [Step("", plugins, f"registry unreadable ({e}); not touched")]
    keys = [k for k in (installed.get("plugins") or {}) if k.split("@", 1)[0] == "teyla"]
    markets = [m for m, e in known.items() if _is_teyla_marketplace(m, e)]
    steps = []
    claude = _claude_bin()
    for key in keys:
        if claude:
            steps.append(Step("run", f"claude plugin uninstall {key}", "the Claude Code plugin",
                              lambda key=key: _run([claude, "plugin", "uninstall", key])))
        else:
            def drop_plugin(key=key):
                plugin_install.uninstall(key, plugins_dir=plugins)
                _rmdir_empty(plugins / "cache" / key.split("@", 1)[-1] / "teyla", plugins / "cache")
            steps.append(Step("remove", f"{plugins / 'installed_plugins.json'}[{key}] + its cache copy",
                              "the plugin rows Teyla wrote (no `claude` binary here)", drop_plugin))
    for m in markets:
        entry = known[m]
        src = entry.get("source") or {}
        if claude:
            steps.append(Step("run", f"claude plugin marketplace remove {m}", "the marketplace entry",
                              lambda m=m: _run([claude, "plugin", "marketplace", "remove", m])))
        else:
            def drop(m=m):
                k = plugin_install._load_json(plugins / "known_marketplaces.json")
                if m in k:
                    plugin_install._backup(plugins / "known_marketplaces.json")
                    k.pop(m)
                    plugin_install._write_json(plugins / "known_marketplaces.json", k)
            steps.append(Step("remove", f"{plugins / 'known_marketplaces.json'}[{m}]", "the marketplace entry", drop))
            loc = pathlib.Path(str(entry.get("installLocation") or ""))
            # only a clone Teyla or `claude` made under marketplaces/ — a `directory` source is
            # somebody's checkout and is never deleted
            if src.get("source") == "github" and (plugins / "marketplaces") in loc.parents and loc.is_dir():
                steps.append(Step("remove", loc, "the marketplace clone", lambda loc=loc: _rm(loc)))
        if src.get("source") == "directory":
            steps.append(Step("", src.get("path"), "the marketplace's source directory — a checkout, not Teyla's to delete"))
    if not claude:
        # `claude plugin install` also enables the plugin in settings.json; Teyla's own install
        # does not, and editing the harness's settings by hand is not Teyla's to do
        try:
            enabled = json.loads((home / ".claude" / "settings.json").read_text()).get("enabledPlugins") or {}
        except (OSError, ValueError, AttributeError):
            enabled = {}
        for k in enabled:
            if str(k).split("@", 1)[0] == "teyla":
                steps.append(Step("", f"{home / '.claude' / 'settings.json'} enabledPlugins[{k}]",
                                  "written by `claude plugin install`, not by Teyla; remove the key by hand"))
    return steps


def _teyla_dir(home: pathlib.Path, keep_data: bool) -> list[Step]:
    d = home / ".teyla"
    steps = []
    other = os.environ.get("TEYLA_HOME")
    if other and pathlib.Path(other).expanduser() != d and pathlib.Path(other).expanduser().exists():
        # a second profile somebody chose: its location is theirs, so it is reported, not guessed at
        steps.append(Step("", other, "TEYLA_HOME points here: a second Teyla profile; remove it yourself"))
    if not d.exists():
        return steps
    if not keep_data:
        return steps + [Step("remove", d, "Teyla's state: config, caches, doctor, reminders, hooks, wrappers, control plane",
                             lambda: _rm(d))]
    for p in (d / "hooks", d / "daily.sh", d / "weekly.sh"):
        if p.exists():
            steps.append(Step("remove", p, "code, not data (--keep-data keeps the rest)", lambda p=p: _rm(p)))
    steps.append(Step("", d, "--keep-data"))
    return steps


def _reports(home: pathlib.Path, cfg: dict) -> list[Step]:
    steps = []
    pol = home / ".agents" / "POLICY.md"
    if pol.exists():
        steps.append(Step("", pol, "your file (Teyla wrote it from a template once); to remove: rm ~/.agents/POLICY.md"))
    for bak in sorted((home / ".agents").glob("POLICY.md.bak-*")) if (home / ".agents").is_dir() else []:
        steps.append(Step("", bak, "a backup `teyla policy refresh` made of your file"))
    plugins = home / ".claude" / "plugins"
    for bak in sorted(plugins.glob("*.json.bak-*")) if plugins.is_dir() else []:
        steps.append(Step("", bak, "a registry backup `teyla plugin` made"))
    roots = []
    for key in ("code_root", "ops_root"):
        r = _expand(str(cfg.get(key) or ""), home)
        if str(r) and r.is_dir() and r not in roots:
            roots.append(r)
    for root in roots:
        repos = [root] + sorted(p for p in root.iterdir() if p.is_dir() and not p.name.startswith("."))
        for repo in repos:
            if (repo / ".teyla").is_dir():
                steps.append(Step("", repo / ".teyla", "corrections captured in this repo; delete it yourself if unwanted"))
            rules = sorted((repo / ".claude" / "rules").glob("*.md")) if (repo / ".claude" / "rules").is_dir() else []
            if rules:
                steps.append(Step("", repo / ".claude" / "rules", f"{len(rules)} rule file(s) — this repo's rules, not Teyla's"))
    runs = _expand(str(cfg.get("ops_root") or "~/ops"), home) / "startup" / "os" / "ai-dev" / "runs"
    if runs.is_dir():
        steps.append(Step("", runs, "the weekly routine's reports"))
    return steps


def plan(home: pathlib.Path | None = None, keep_data: bool = False) -> list[Step]:
    """Every step, in the order they run: stop what runs on its own, then unwire the harnesses,
    then the state. Read-only: builds the list, changes nothing."""
    from . import config
    home = home or pathlib.Path.home()
    cfg = config.load(home / ".teyla" / "config.toml")  # read before ~/.teyla goes
    return (_launch_agents(home) + _plugin(home) + _hooks(home) + _skills(home) + _hermes(home)
            + _policy_links(home) + _claude_md(home) + _teyla_dir(home, keep_data) + _reports(home, cfg))


def run(dry: bool = False, keep_data: bool = False, home: pathlib.Path | None = None) -> tuple[list[str], int]:
    """(lines, failures). A step that raises, or a command that exits non-zero (`claude plugin
    uninstall` unauthenticated, say), is a failure: reported with its output, counted, and the
    remaining steps still run — one stuck piece must not strand the rest wired."""
    steps = plan(home, keep_data)
    lines, failed = [], 0
    for s in steps:
        if s.fn is not None and not dry:
            try:
                res = s.fn()
            except Exception as e:  # noqa: BLE001
                res = (1, f"{type(e).__name__}: {e}")
            if isinstance(res, tuple) and len(res) == 2 and isinstance(res[0], int) and res[0] != 0:
                failed += 1
                lines.append(f"FAILED  {s.verb} {s.target}: exit {res[0]}: {str(res[1]).strip()[-400:]}")
                continue
        lines.append(s.line(dry))
    if not any(s.fn for s in steps):
        lines.insert(0, "nothing of Teyla's left to remove on this machine")
    lines.append("")
    if failed:
        lines.append(f"{failed} step(s) FAILED — fix what they name and run `teyla uninstall` again (it is idempotent)")
    lines.append("the teyla command itself: uv tool uninstall teyla   (or: pipx uninstall teyla)")
    return lines, failed


def cmd_uninstall(args):
    lines, failed = run(dry=args.dry, keep_data=args.keep_data)
    for line in lines:
        print(line)
    return 1 if failed else 0


def register(sp):
    q = sp.add_parser("uninstall", help="undo every write Teyla made on this machine (--dry lists them)")
    q.set_defaults(fn=cmd_uninstall)
    q.add_argument("--dry", action="store_true", help="print every action, touch nothing")
    q.add_argument("--keep-data", action="store_true", help="keep ~/.teyla (config, reminders, receipts); still unwire everything")
    return q
